### ISSUE TITLE
Streak mode no highlight of the first match?

### ISSUE THREAD

**Issue by liujoey** [justinmk/vim-sneak#101]
when I trigger the streak mode, it jumps to the first match and highlights other matches. This is great but the problem is there's no highlight or indicator or cursor blink or whatever on the first match. Some times I can't even find where's my cursor. Would you please add highlight of the first match with a different color like `yellow` so at least I know where I am.

**Comment by liujoey** [comment]
Hello @justinmk , it occurs again in neovim with iTerm2 OS X El Capitan.
I'm using gruvbox color scheme and my iTerm2 has the same gruvbox shell script to setup the 256 color palette.

**Comment by justinmk** [comment]
what about `:hi Normal` ?

**Comment by liujoey** [comment]
:hi Normal
Normal         xxx ctermfg=237 ctermbg=229 guifg=#3c3836 guibg=#fdf4c1
