### ISSUE TITLE
homerow exit after streak match?

### ISSUE THREAD

**Issue by shoshin** [justinmk/vim-sneak#122]
Hello and thanks @justinmk for a very nicely done plugin!

One question: 

I'm frequently finding myself in the following scenario: I've "streaked" for a combination with > 2 matches but my intended target was 1st and the cursor was moved immediately where I wanted it to be. At this point I'd like to be able to exit streak mode without moving the cursor (ie not using space) and without my fingers leaving the home row (ie not using ESC). I've tried several combinations of settings but haven't found a way to get this behavior. This came up after I noticed that I am (seemingly) more efficient (or at least it seems more predictable) when my target is _not_ the first match and I can both jump to the target and exit streak mode by hitting the usually homerow target label.  

Any suggestions?  

Thanks again!

**Comment by justinmk** [comment]
>  I'd like to be able to exit streak mode without moving the cursor (ie not using space) and without my fingers leaving the home row (ie not using ESC). 

You can exit via `<space>` now and it won't move the cursor. You can change it to some other key (that isn't a target label) like so:

    let g:sneak#streak_esc = "?"

**Comment by aeosynth** [comment]
this doesn't quite work for me, as i'm still not in normal mode after pressing `<space>`, so it's more effort when the desired target is the first match

#159

**Comment by superDuperCyberTechno** [comment]
Would it be possible to label _every_ hit (including the first one)?
