### ISSUE TITLE
Terminal key codes broken when <Esc> is mapped

### ISSUE THREAD

**Issue by wilywampa** [justinmk/vim-sneak#133]
After a sneak motion, `<Esc>` is mapped to `sneak#cancel()`. In terminal Vim, this causes wrong things to happen when I press special keys after sneaking. For example, `<Left>` is `<Esc>OD`, and pressing `<Left>` after sneaking opens a new line above (`O`) and types a `D` instead of doing what I have `<Left>` mapped to do.

It seems this was discussed here but I guess not fully tested: https://github.com/justinmk/vim-sneak/issues/106. Maybe the map should be made optional as discussed there. I use `<C-l>` to cancel sneak.

**Comment by bohrshaw** [comment]
Hi @justinmk, I also ran into this issue as I'm one of these guys who have meta chords in normal mode. Moreover the current mapping would override the user defined one if it happens that `<Esc>` is already mapped by the user. So I can't agree more this should be optional.
And in [codes](https://github.com/justinmk/vim-sneak/blob/master/plugin/sneak.vim#L199), `\<Esc>` in map-rhs is redundant and I think is the cause to the error bell I would heard.

**Comment by bohrshaw** [comment]
Hi @justinmk, I also ran into this issue as I'm one of these guys who have meta chords in normal mode. Moreover the current mapping would override the user defined one if it happens that `<Esc>` is already mapped by the user. So I can't agree more this should be optional.
And in [codes](https://github.com/justinmk/vim-sneak/blob/master/plugin/sneak.vim#L199), `\<Esc>` in map-rhs is redundant and I think is the cause to the error bell I would heard.

**Comment by justinmk** [comment]
@bohrshaw Good obsevation about the error bell, I never noticed it because I disable them. However I am not sure it's because of the "redundant" `<esc>`; that was (orignally, at least) require so that a "real" escape would occur. But then it was changed to `nmap` for some other reason I forget, and maybe now that causes it to hit the recusion limit, causing an error bell?

**Comment by justinmk** [comment]
Anyways, I will disable this feature by default.

**Comment by bohrshaw** [comment]
@justinmk You're right that `"\<esc>"` is not redundant in `nmap <expr> <silent> <esc> sneak#cancel() . "\<esc>"`. As upon the command parsing, it hasn't been mapped by this command. And `nmap` makes sense in case `<esc>` is already mapped by the user.
And it seems Vim doesn't provide a simple way to backup a mapping definition and later restore it. Thus any key mapped to `sneak#cancel()` in normal mode would potentially conflict with a user defined one.

On the other hand, I personally never run into a situation requiring a call to `sneak#cancel()` manually. And even if I does, I'll just press for example `l` to trigger some auto-commands.

**Comment by justinmk** [comment]
Even `nnoremap <esc> <esc>` causes the behavior described by @wilywampa. So, this feature is now disabled by default. Thanks for reporting.

**Comment by justinmk** [comment]
@bohrshaw This issue doesn't seem to affect Neovim. If you use Neovim (a fairly recent build), can you confirm? I will probably re-enable this feature if `has("nvim")` is detected.

**Comment by bohrshaw** [comment]
@justinmk I have just confirmed and I appreciate this revisiting as `<Esc>` is really a sensible key-binding.
