### ISSUE TITLE
suggest clever-f.vim to free up ; and , for vim-sneak

### ISSUE THREAD

**Issue by Konfekt** [justinmk/vim-sneak#134]
Many potential users are reluctant to overwrite `s/S`. How about suggesting clever-f.vim to free up `;` and `,` for   `nmap ; <Plug>Sneak_s` and `nmap , <Plug>Sneak_S` ? This matches well with being able to jump to the next match by iteratively hitting `;` and `,`., just as `clever-f.vim` does.

**Comment by justinmk** [comment]
@Konfekt Did you try `g:sneak#s_next` (combined with  `nmap ; <Plug>Sneak_s` and `nmap , <Plug>Sneak_S`)?

https://github.com/justinmk/vim-sneak/blob/master/doc/sneak.txt#L331-L340

**Comment by Konfekt** [comment]
Yep. That's why steak can content itself withbtwo mappings like ; and , after all.
