### ISSUE TITLE
Less obtrusive and distracting Streak Mode

### ISSUE THREAD

**Issue by bohrshaw** [justinmk/vim-sneak#136]
Personally I find the current "background/foreground color switch" and "syntax off and on" in Streak Mode obtrusive and a little distracting to my workflow.
I'm aware that it's used to deal with situations like "very long lines" or "multi-bytes" etc. But the most common text I deal with everyday is all ASCII, in which case I really hope Streak Mode can be less obtrusive, just like all the other native motions.
In ideal, I'm thinking concealing a target character without any highlight. I don't know whether it's feasible or not.

**Comment by justinmk** [comment]
Sadly, conceal doesn't override syntax "keywords", so it close to useless if the syntax is not cleared. I believe @chrisbra sent a patch to fix this, years ago.

**Comment by chrisbra** [comment]
Hi Justin!

On Do, 12 Feb 2015, Justin M. Keyes wrote:

> Sadly, conceal doesn't override syntax "keywords", so it close to useless if the syntax is not cleared. I believe @chrisbra sent a patch to fix this, years ago.

I made a match_conceal patch¹ a while ago. Not sure it would helped you 
here. Perhaps I should look into extending it as Bram suggested.

¹https://groups.google.com/d/msg/vim_dev/8bKa98GhHdk/VOzIBhd1m8YJ

Best,
Christian
-- 
Hallo Handeincremer!

**Comment by justinmk** [comment]
@chrisbra Hi! That is exactly the patch I was referring to.

**Comment by nhooyr** [comment]
Any updates?

**Comment by justinmk** [comment]
@nhooyr That patch was merged, I haven't done the work to use it yet. vim-easymotion has logic to use it, which could be borrowed (as vim-easymotion did with the "conceal" method first used by sneak ;)
