### ISSUE TITLE
Streak within the current line

### ISSUE THREAD

**Issue by bohrshaw** [justinmk/vim-sneak#137]
Motion within the current line is very common especially in operator pending mode. And when there's only one candidate to jump to within the current line, I expect Streak Mode would not be triggered at all to save me a key stroke.
So I think Streak Mode could optionally restrict the region of motion to the current line.

**Comment by bohrshaw** [comment]
"Sneak in the current line" is less straight than "Streak" when there's more than 2 candidates. So I prefer Streak Mode and hope it can be improved in this common user case.

**Comment by justinmk** [comment]
With the change of default labels in  ebb01c9 I consider "single line" mode to be unnecessary. When the first match is the correct match, one can just type the next command without explicitly exiting Sneak label-mode, and it is very unlikely that a label will be unintentionally chosen. (Adjust `g:sneak#target_labels` as necessary if some of the default labels are mapped to custom actions)
