### ISSUE TITLE
Clever-s is not working

### ISSUE THREAD

**Issue by kshenoy** [justinmk/vim-sneak#140]
1. As described in `:h sneak-clever-s`, pressing `s` after invoking sneak should move me to the next match. Is this enabled by default or do I have to set something to get it working?

2. Is it possible to achieve the same for f/F/t/T as well? I tried fiddling with `<Plug>Sneak_f` by setting it to `:<C-U>call sneak#wrap('', 1, 0, 1, 1)<CR>`. Is this the right way to go about it? If yes, then what did I miss, it doesn't seem to be working for me. 

3. What's the best way to not highlight the sneak target? I tried placing `hi clear SneakPluginTarget` both in bundle.vim and ~/.vim/after/plugin/plugin.vim and neither approach seemed to work.

And, thanks for the awesome plugin :+1:

**Comment by justinmk** [comment]
1. It's disable by default, you need:

    let g:sneak#s_next = 1

2. It should work for f/F/t/T, too. 

3. Since `autoload/sneak/hl.vim` is lazy-loaded, your highlight is getting clobbered. But this seems to work:

```vim
hi link SneakPluginTarget Normal
```

You could also add 

```vim
hi link SneakStreakTarget Normal
hi link SneakStreakMask Normal
```

but that will make streak-mode difficult to use.

**Comment by kshenoy** [comment]
Thanks, works perfectly now :)
