### ISSUE TITLE
Forcing streak-mode behaves the same as passive/smart streak-mode

### ISSUE THREAD

**Issue by chaucerbao** [justinmk/vim-sneak#141]
The docs say:
```
To force streak-mode always (instead of passively letting Sneak decide when to
enter streak-mode), create a mapping to <Plug>(SneakStreak). For example:

    nmap s <Plug>(SneakStreak)
    nmap S <Plug>(SneakStreakBackward)
```

However, the behavior still mimics "passive/smart" streak-mode in that whenever there are only 2 matches it will jump to the first match and highlight the second, without creating a jump target.

**Comment by justinmk** [comment]
Thanks for the report. I guess no one uses that feature, because it's been that way for 1 year :) Should be fixed now.

**Comment by chaucerbao** [comment]
Heh, no, I've been using it.  Just finally decided to report it, 'cuz I thought maybe I've been doing something wrong. :)
