### ISSUE TITLE
Streak function with input string

### ISSUE THREAD

**Issue by NigoroJr** [justinmk/vim-sneak#145]
Hello, thanks for the awesome plugin. I've been using vim-seek for a while and switched to vim-sneak, and I'm really loving it!

I tried out the streak mode and thought it's pretty neat, too. However, I was wondering if there's any way I can manually start streak mode while sneaking. Here's an example to demonstrate my scenario (it also shows my current settings).

```vim
" [C]ursor here
let g:sneak#s_next = 1
let g:sneak#reset = 1
let g:sneak#streak = 1
" let g:sneak#target_labels = '1234567890'
```

Typing `ssn` will start streak mode since there is no `sn` on the current line. However, since I like the clever-s behavior, I would like to be able to hit `s` if it's only a several times rather than typing the target character that streak shows me. On the other hand, if it's _not_ just a several times, like:

```
[C]ursor here
sneak sneak sneak sneak sneak sneak...
sneak...
sn...
...
```

, it would be nicer to have streak take me to the target in just one keystroke. Using a hypothetical function `sneak#streak()` that takes a search string as an argument, I came up with this (hypothetical) mapping that you can start streak mode with `<Space>` while sneaking:

```vim
nmap <silent> <expr> <Space> sneak#is_sneaking() ?
    \ ':<C-u>call sneak#streak(sneak#state().input)<CR>' : '<Space>'
```

Do you think this doable in some (other) way?

Thanks!

**Comment by justinmk** [comment]
Sorry, I don't understand the request. Does https://github.com/justinmk/vim-sneak/issues/119 help?

**Comment by NigoroJr** [comment]
I actually tried that, but `<Plug>(SneakStreak)` does not start streak mode when you're sneaking. It just moves to the next match. I figured it's an intended behavior, but is that a bug?

**Comment by NigoroJr** [comment]
Can't remember what I was asking for or why... Closing.
