### ISSUE TITLE
De-coloring of not matching text does not disappear if there's only one match.

### ISSUE THREAD

**Issue by PonderingGrower** [justinmk/vim-sneak#147]
Here's a video of the behaviour:

[![asciicast](https://asciinema.org/a/b9cl8vof2hbz611d0tchw16iv.png)](https://asciinema.org/a/b9cl8vof2hbz611d0tchw16iv)

It only leaves after any action is taken. For example like `hjlk` movements in that video.

I'm using neovim(NVIM 0.0.0-alpha+201506252226, 4aa6279a6bbaed0c6ea98ae5d04259df267ca292).

**Comment by justinmk** [comment]
I watched the video 5 times, but I don't get it. Are you saying it should not go into streak-mode? What mappings and settings are you using?

**Comment by PonderingGrower** [comment]
Well, I expected it to stop sneak mode if there's only one available target on the screen.

Is that the intended behaviour? For it to say in sneak mode? And if so is it possible to change it?

**Comment by justinmk** [comment]
It depends, are you using `let g:sneak#streak =1` (which is "smart" and behaves as you expect) *or* are you mapping to `<Plug>SneakStreak` (which is not "smart", it always enters streak-mode, by design).

**Comment by PonderingGrower** [comment]
Ooooooh, now I see. I wasn't aware of that distinction. I have not read the doc file thoroughly enough.

Thanks man, I guess this behaviour isn't that annoying. I think I prefer to map `<Plug>SneakStreak` mapped directly since I don't really like being surprised by which mode I get, sneak or streak.

I figure this can be closed a s this is intended behaviour.

Cheers man, thanks for making a great, great plugin.

**Comment by justinmk** [comment]
> I don't really like being surprised by which mode I get, sneak or streak.

Neither do I. But if you set `target_labels` to something like this:

    let g:sneak#target_labels = ";sftunq/SFGHLTUNRMQZ?0"

Then you can always know that you will never accidentally select a label. I've been meaning to make these the default labels.
