### ISSUE TITLE
dot repeat with ct and one-character sneak

### ISSUE THREAD

**Issue by saliola** [justinmk/vim-sneak#150]
Hello. Thanks for this plugin. I don't use all the features, but I really like the one-character sneak versions of f and t. It is with the latter that I am experience an issue.

In short, after a `ct<char>` edit, the dot repeat is broken.

Here is a minimal working example that illustrates the issue.

 * Install (only) vim-sneak in `~/.vim` and create a `.vimrc` containing only the two following lines:

        omap t <Plug>Sneak_t

   (You can include all the one-character `Sneak_t` commands, but the problem really seems to be with the `omap` version.)

 * Open a file and type the following:

        1234|
        1234|
        1234|

 * Go to the first character of the first line and execute:

        ct|abcd<Esc>

 * Then move to the first character of the second line and hit `.`.

 * Then move to the first character of the third line and hit `.`.

 * I expect to see:

        abcd|
        abcd|
        abcd|

 * But instead I see:

        abcd|
        bcd234|
        cd234|

Vim version:

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul  8 2015 01:02:35)
    Included patches: 1-769

Hope this helps. Let me know if you need any more information.

**Comment by justinmk** [comment]
@saliola Thanks for the detailed report. 

> Install (only) vim-sneak

Well, dot-repeat requires https://github.com/tpope/vim-repeat . What version of repeat.vim are you using?

I can't reproduce on Vim 7.3, nor Neovim latest. I certainly would have noticed this bug, I think...

I will try on a more recent version of Vim when I get a chance. Can you try Vim 7.3?

**Comment by saliola** [comment]
Thanks for the prompt reply. I forgot about the vim-repeat dependency. But I have vim-repeat installed normally and I still have issues occasionally while repeating with `ct`. I'll have to try to debug this further.

**Comment by saliola** [comment]
I think the problem is a conflict with @junegunn's vim-peekaboo. I'm not sure whether I should report this here or with vim-peekaboo.

To see the problem, follow the instructions above with three plugins (most recent versions):

    https://github.com/junegunn/vim-peekaboo
    https://github.com/tpope/vim-repeat
    https://github.com/justinmk/vim-sneak

I now see:

    abcd|
    |
    1234|

but after the second `.` repeat, I see the following at the bottom of the screen:

    :call sneak#wrap(v:operator, sneak#util#getc(), sneak#util#getc(), sneak#util#getc(), sneak#util#getc())

and I need to hit `Ctrl-C` a couple of times to get my cursor back.

As I said, I'm not sure whether this should be reported here.

**Comment by justinmk** [comment]
What version of Repeat.vim?

**Comment by saliola** [comment]
The most recent version.

**Comment by justinmk** [comment]
Looks like this is a known issue with peekaboo: https://github.com/junegunn/vim-peekaboo/issues/30

**Comment by saliola** [comment]
@justinmk thanks again for your prompt reply.
