### ISSUE TITLE
Support vim-multiple-cursors ???

### ISSUE THREAD

**Issue by DemonCloud** [justinmk/vim-sneak#151]
When i do with multiple cursor,

`f` `s` get issue！！！

https://github.com/terryma/vim-multiple-cursors

**Comment by justinmk** [comment]
Can you provide more details?

**Comment by DemonCloud** [comment]
@justinmk 

I record GIF to you. use the recommend setting

#### use ``f``
![bug](https://cloud.githubusercontent.com/assets/7436361/8668469/64529778-2a46-11e5-9284-df82ff9c2c24.gif)
#### use ``t``
![bugtwo](https://cloud.githubusercontent.com/assets/7436361/8668477/7552d600-2a46-11e5-8991-b11c6c5fbcd4.gif)

#### Setting
```VimL
    "replace 'f' with 1-char Sneak
    nmap f <Plug>Sneak_f
    nmap F <Plug>Sneak_F
    xmap f <Plug>Sneak_f
    xmap F <Plug>Sneak_F
    omap f <Plug>Sneak_f
    omap F <Plug>Sneak_F
    "replace 't' with 1-char Sneak
    nmap t <Plug>Sneak_t
    nmap T <Plug>Sneak_T
    xmap t <Plug>Sneak_t
    xmap T <Plug>Sneak_T
    omap t <Plug>Sneak_t
    omap T <Plug>Sneak_T
```

#### my dotfile 
https://github.com/DemonCloud/dotfile-YVIM

#### Multiple Cursor
https://github.com/terryma/vim-multiple-cursors

**Comment by justinmk** [comment]
@DemonCloud  Does https://github.com/tpope/vim-surround work with multiple cursors? What other motion plugin(s) work with multiple-cursors? Is there some registration function that sneak needs to call in order to work with multiple-cursors?

**Comment by romgrk** [comment]
Same issue here. 
I have been reading both this and multi-cursors code to try to come up with a fix. The `sneak` part is fine, everything is well exposed (functions & global state). 
The issue is `multi-cursors` isn't customizable enough. (related: https://github.com/terryma/vim-multiple-cursors/issues/199)
I'll keep investigating and update if I find a workaround.

**Comment by justinmk** [comment]
Can't do much about this. Though the research here is valuable.
