### ISSUE TITLE
Awesome highlighting behaviour for / as well

### ISSUE THREAD

**Issue by tknuth** [justinmk/vim-sneak#154]
Hi,

Great work! I particularly like how sneak unhighlights the matches when starting another move.

Would it be possible to offer this, either as a feature or as a hack in .vimrc besides the plugin, for the `/` as well? `/`, as you probably know, retains the highlighting even if you move on, and only a manual `:set invhlsearch` removes it.

Thank you!

**Comment by lydell** [comment]
You might be interested in [vim-oblique](https://github.com/junegunn/vim-oblique).

**Comment by justinmk** [comment]
Yeah, that's what I was thinking. It's out of scope for sneak to make love to `/`.

Thanks for your interest.

**Comment by tknuth** [comment]
vim-oblique is totally what I needed. Thank you guys!
