### ISSUE TITLE
Operator should be a one-time sneak by default

### ISSUE THREAD

**Issue by tbastos** [justinmk/vim-sneak#157]
I have to constantly hit ESC when using sneak as an operator because by default it enters in sneak mode (highlighting the next matches) once I'm done with the operation. Does this behavior ever make sense? IMHO when used as an operator it should just do the textobj thing and not enter in sneak mode. It's disturbing to have to hit ESC after every operation.

Thanks for the plugin!

**Comment by justinmk** [comment]
Existing behavior was considered a feature, as well as matching the behavior of Vim's built-in search, but I agree it doesn't seem justifiable, and this may be one of the cases where sneak's behavior _should_ deviate from `/`.

**Comment by tbastos** [comment]
Thanks!
