### ISSUE TITLE
Visual bug with custom mappings and inconsistency with native vim behavior.

### ISSUE THREAD

**Issue by thang1thang2** [justinmk/vim-sneak#158]
I'm trying to set up vim-sneak so that f/F and t/T work as two character searches with sneak on. It's taken me several hours to try and figure out what keeps happening, but I've got a pretty good idea at this point.

Some settings for reference:

    let g:sneak#streak = 0
    let g:sneak#use_ic_scs = 1

    nnoremap <silent> t :<c-u>call sneak#wrap('', 2, 0, 0, 1)<cr>
    nnoremap <silent> T :<c-u>call sneak#wrap('', 2, 1, 0, 1)<cr>
    xnoremap <silent> t :<c-u>call sneak#wrap(visualmode(), 2, 0, 0, 1)<cr>
    xnoremap <silent> T :<c-u>call sneak#wrap(visualmode(), 2, 1, 0, 1)<cr>
    onoremap <silent> t :<c-u>call sneak#wrap(v:operator, 2, 0, 0, 1)<cr>
    onoremap <silent> T :<c-u>call sneak#wrap(v:operator, 2, 1, 0, 1)<cr>
    
    nnoremap <silent> f :<c-u>call sneak#wrap('', 2, 0, 1, 1)<cr>
    nnoremap <silent> F :<c-u>call sneak#wrap('', 2, 1, 1, 1)<cr>
    xnoremap <silent> f :<c-u>call sneak#wrap(visualmode(), 2, 0, 1, 1)<cr>
    xnoremap <silent> F :<c-u>call sneak#wrap(visualmode(), 2, 1, 1, 1)<cr>
    onoremap <silent> f :<c-u>call sneak#wrap(v:operator, 2, 0, 1, 1)<cr>
    onoremap <silent> F :<c-u>call sneak#wrap(v:operator, 2, 1, 1, 1)<cr>

I've determined that sneaking in reverse respects the usage of forcing behavior (ie using 'v', 'V' or 'c-v'). By forcing behavior, I mean explicitly setting something to be inclusive/exclusive, linewise/characterwise, etc. However, sneaking forward doesn't. If I type a command such as `dtab`, it doesn't matter if it's `dtab`, `dvtab`, `dVtab` or `d^Vab`.

There is an exception; if I use '2' for the third number (aka "like / search" inclusive behavior), the commands work. However, that emulates the functionality of t for forward searching and the functionality of f for backwards searching... (Who came up with that, anyway?)

Technically with the above settings, everything works "fine". However, being able to use streak would be really cool. Unfortunately, whenever I enable it, I'm left over in visual mode after the command and it's very annoying. I haven't found out a way to get everything to work correctly (while leaving sneak enabled) yet. I'm fairly sure it has to do with sneak not respecting 'v' options when sneaking forward.

**Comment by justinmk** [comment]
> However, being able to use streak would be really cool. 

I'm confused by the mention of "streak". Is streak-mode the problem, or plain old sneak-mode? (Yeah the name was probably a mistake :).

**Comment by thang1thang2** [comment]
Hopefully I can clarify. Currently my goal is to be able to use all of the features of vim-sneak (including streak) with a two character f and t binding, and proper exclusive/inclusive support. As it is, two character sneak with f and t binding only mostly works even if streak is disabled. If streak is enabled, it breaks with an ugly visual mode bug. Furthermore, if I want to manually toggle exclusive/inclusive behavior (with v/V/^V, etc) it doesn't work for forward sneaks, it only works if I sneak backwards.

I probably should've split this into two issues, but I spent about 8 hours trying to chase down what was causing what and the mess of a paragraph above is the sleep deprived results of my procrastination from studies...

**Comment by justinmk** [comment]
@thang1thang2 Sorry, I can't reproduce any of those issues. There are even tests for inclusive/exclusive behavior, and the tests are passing...

Maybe there is a conflicting plugin or autocmd in your config.
