### ISSUE TITLE
fast streak exit

### ISSUE THREAD

**Issue by aeosynth** [justinmk/vim-sneak#159]
when i press `space` to escape streak mode, i'm still in sneak mode; i would like to go directly to normal mode

edit: `streak_esc` could probably be dropped if the first match had a label. giving the first match special behavior is confusing.

**Comment by justinmk** [comment]
Closed by a1788cc38c9488aa77c03da0b7ca8a4a6723ab4c

**Comment by justinmk** [comment]
> streak_esc could probably be dropped if the first match had a label. giving the first match special behavior is confusing.

I don't understand. You don't want to jump to the first match?

**Comment by aeosynth** [comment]
you could implement the default `streak_esc` by making `space` the first match character. pressing `space` to jump to the first match would be equivalent to auto jumping and pressing `space` to exit. there doesn't have to be a separate concept for this.

**Comment by justinmk** [comment]
@aeosynth That's not a bad idea, but you actually don't have to press space at all. One of the strongest features of streak-mode is that non-target keys fall through to Vim and act immediately. The only potential issue there is if a target label uses the same key as an action. But that isn't an issue if one configures the labels to omit any keys that one would want to use following a navigation. I use this config, and plan to make it the default:

https://github.com/justinmk/config/blob/master/.vim/vimrc#L164

**Comment by justinmk** [comment]
One other issue with the fall-through feature is discussed here:

https://github.com/justinmk/vim-sneak/pull/123#issuecomment-53735342

I have a solution for that which I hope to work on now that [dirvish](https://github.com/justinmk/vim-dirvish) is reaching maturity.

**Comment by aeosynth** [comment]
> One of the strongest features of streak-mode is that non-target keys fall through to Vim and act immediately.

that feature has a lot of cognitive burden, to sometimes save a single keystroke. personally, i would always press space, and have sane (for me) labels.

**Comment by justinmk** [comment]
If it has cognitive burden then it is of course useless. But it should not have cognitive burden if it is trustworthy. I've found that choosing non-conflicting labels results in a predictable behavior. Where is the cognitive burden in that case?

**Comment by aeosynth** [comment]
let's say your config becomes the default. i sneak, auto jump to the first match, then want to use a motion command. `jk` work fine, `HLM` don't. i can't trust that i can perform arbitrary motions after a sneak; i need to learn and remember which motions are guaranteed to not be labels.

let's say i create my own labels, so learning/remembering is not an issue. then there's still a burden when updating my config, i have to dance around these labels and decide whether to change the list, or put a new mapping in maybe a more awkward spot.

i simply ignore this feature, because i don't want to care about labels.
