### ISSUE TITLE
Unmapping custom mappings "f" or "t"

### ISSUE THREAD

**Issue by sheoak** [justinmk/vim-sneak#160]
I'm using *bépo* keyboard layout (French Dvorak) where `t` is on the home row, so it is remap to `j`.
When I'm using the native *f* or *t* (*j* for me) commands, my map for *t* is deleted. I noticed this code in sneak.vim, where *f* and *t* are hardcoded:

    for k in ['f', 't'] "unmap the temp mappings
        if g:sneak#opt[k.'_reset']
          silent! exec 'unmap '.k
          silent! exec 'unmap '.toupper(k)
        endif
    endfor

I’m not sure if this case is just not implemented or if it's a bug, or just me not using sneak properly?

**Comment by justinmk** [comment]
@sheoak What do you mean by "t is remapped to j"? As in `nnoremap t j` ?

Out of the box, Sneak tries to "listen" for `f` and `t` by setting a temporary mapping which is immediately removed on `f` or `t` invocation. (There is literally no other way to do this in Vim)

You can see in `s:ft_hook()` that if `f` or `t` are already mapped, Sneak will _not_ touch them:

```vim
func! s:ft_hook() "set up temporary mappings to 'hook' into f/F/t/T
  for k in ['f', 't']
    for m in ['n', 'x']
      "if user mapped anything to f or t, do not map over it; unfortunately this
      "also means we cannot reset ; or , when f or t is invoked.
      if g:sneak#opt[k.'_reset'] && maparg(k, m) ==# ''
        call s:map_reset_key(k, m) | call s:map_reset_key(toupper(k), m)
      endif
    endfor
  endfor
endf
```

If you want to disable this explicitly, you can do this:

```vim
let g:sneak#f_reset = 0
let g:sneak#t_reset = 0
```

See `:help sneak-options` for details.

Closing this but please feel free to share more details.

**Comment by justinmk** [comment]
> When I'm using the native f or t (j for me) commands, my map for t is deleted

This is extremely confusing. _Without_ loading sneak, what does `:echo maparg('t', 'n')` report? Then _with_ sneak, what is the result?

**Comment by sheoak** [comment]
I think it's because I'm remapping them in a plugin I’m coding. I remapped them like this: 

    noremap t j
    noremap j t

Let me do some testing with the help you gave me and I'll tell you if it's working. Thanks!

**Comment by justinmk** [comment]
@sheoak You could load sneak _after_ that plugin, then it will behave. Or set the options mentioned above explicitly.

**Comment by sheoak** [comment]
The code you pasted is executed when using sneak, but "j" is unmap when I'm using j (not when I’m using f, which is not remapped). The line:

    call s:map_reset_key(k, m) | call s:map_reset_key(toupper(k), m)

is not executed when I press "j".

Moving the code:

    noremap t j
    noremap j t


in my .vimrc does the same.

**Comment by sheoak** [comment]
:echo maparg('t', 'n')
    > j

    :echo maparg('f', 'n')
    > nothing

**Comment by sheoak** [comment]
Ok I found out why, I had an option undeleted in another file, but I now have a similar problem at a different moment. If it works for you when remapping t, you can close the ticket, I will do more testing tomorrow and open a new one if I can't fix it. I will implement a "bepo version" of your mappings in my plugin, thank you for your help!

**Comment by sheoak** [comment]
Ok, I was missing this in my .vimrc : 

    let g:sneak#nextprev_t = 'j'

**Comment by justinmk** [comment]
:+1: thanks for followup
