### ISSUE TITLE
Allow for single character jump with streak

### ISSUE THREAD

**Issue by ggVGc** [justinmk/vim-sneak#162]
Maybe this is already possible, but I can't figure out how. Somtimes I find myself wanting to use sneak similar to `fanfingtastic`, i.e entering only one character and jumping to the first match over multiple lines. It would be nice to be able to go i.e `s5<esc>`, which would jump to first word beginning with 5. I know there are mappings for f/F/t/T for one-character jumps, but I think one-char jumps would be useful from streak mode also.

**Comment by justinmk** [comment]
See FAQ in readme :)
