### ISSUE TITLE
Comma not works when used as leader key

### ISSUE THREAD

**Issue by chemzqm** [justinmk/vim-sneak#165]
I use comma for leader key
```
let g:mapleader = ','
```
It can search backward with command `F` `f` `T` `t`,  but nothing happens when I search with vim-sneak.
Is there any workaround for this?  
I've used comma as leader key for a long time, and I would like to keep it.

**Comment by justinmk** [comment]
It's documented:

https://github.com/justinmk/vim-sneak/blob/master/doc/sneak.txt#L129
