### ISSUE TITLE
Remapping comma

### ISSUE THREAD

**Issue by alcesleo** [justinmk/vim-sneak#167]
Hi! Is there any way to make the backwards search work with these mappings active:

```viml
nnoremap , :
nnoremap : ,
```

Thank you!

**Comment by justinmk** [comment]
Hi @alcesleo 

If `\` is unmaped then the plugin maps that instead, by default. But, to answer your question precisely:

    nmap : <Plug>SneakPrevious

See `:help sneak-mappings` for full list of `<Plug>` maps.

There are several closed issues with related questions as well.

**Comment by alcesleo** [comment]
Thanks a bunch!

**Comment by jaker-dotcom** [comment]
I'd like to have both the ft search and the sneak reversed. I've mapped it according to the :h sneak-mappings however I only get to work either of those. I guess they're overwriting themselves. How did you solve it @jsborjesson ?
