### ISSUE TITLE
No way to disable SneakPluginTarget highlight

### ISSUE THREAD

**Issue by gyermolenko** [justinmk/vim-sneak#168]
Hi. Is there a way to turn off SneakPluginTarget highlight? 

Currently when i sneak somewhere - highlight is automatically ON (white, grey, magenta, whichever i put in settings).
And when i use s(usual sneak) - there are too many bright spots (sneak candidates) all over the screen.
Or even worse, f/t (one char jump with sneak) - highlights are not limited to one line (but that is another issue/enhancement, i suppose)

Something like this doesn't help: highlight SneakPluginTarget ctermfg=NONE ctermbg=NONE cterm=NONE

It just returns this beautiful magenta background back.
Please advise.

**Comment by justinmk** [comment]
Isn't this the same as https://github.com/justinmk/vim-sneak/issues/171 ?

**Comment by justinmk** [comment]
> Something like this doesn't help: highlight SneakPluginTarget ctermfg=NONE ctermbg=NONE cterm=NONE

This should work:

    highlight link SneakTarget Normal

(Note that `SneakPluginTarget` was renamed to `SneakTarget` in a recent version of the plugin.)
