### ISSUE TITLE
Feature Request: Allow for case insensitivity in symbols

### ISSUE THREAD

**Issue by Alok** [justinmk/vim-sneak#170]
With smartcase/ignorecase set, "sneaking" for a letter (like 'r') will match both 'r' and 'R'. But if I search for ':' and hit ';' (and vice-versa), it doesn't match. Can we have that added as an option. I believe easymotion has code for it and it may be usable.

**Comment by justinmk** [comment]
> I believe easymotion has code for it

EasyMotion has code for everything ;)

I remember when EM added this feature, and frankly I think 99.999% of people will never use it. It seems clever but it ends up being not useful.

People who want this feature should use EM.

Thanks for the request, though.
