### ISSUE TITLE
make sneak match highlight to be optional

### ISSUE THREAD

**Issue by ZzAntares** [justinmk/vim-sneak#171]
Hi, first of all let me congratulate you for this awesome plugin, the only thing I don't like to much is the highlighting, I know I can change the colors used, but I would like to have an option on my .vimrc to just disable it, or a function to a "toggle" like behaviour.

I didn't see in the docs a way to achieve this, is it possible to add this functionality?

Thanks

**Comment by justinmk** [comment]
Thanks for the kind words. Setting the highlight should be enough, though it's too complicated, so that should be fixed.

**Comment by ZzAntares** [comment]
Thanks!, I'll stay tuned.

**Comment by justinmk** [comment]
@ZzAntares At `:help sneak-highlight` there's a note showing how to disable highlighting:

    autocmd ColorScheme * hi! link Sneak Normal

**Comment by ZzAntares** [comment]
👍
