### ISSUE TITLE
Sneaky pattern searches

### ISSUE THREAD

**Issue by cuviper** [justinmk/vim-sneak#172]
Would it be possible to add a sneak mode for regular `/{pattern}` searches?

I just started using vim-sneak, and I'm already very happy to have this replacing the normal `f` and `t` movements for single-char searches.  But now I feel there is a gap when I need to use a pattern search, and `hlsearch` and the jump list don't work the same way.  If I could sneak through those search results too, I think that consistency would be very nice.

I'm not sure if I would commit fully to remapping this.  Sometimes it is nice to have `hlsearch` shown, which is why I enable it at all, but often I only want to get to the right location and clear the highlight.  So I think at first what I would want is to map something like `g/` to a sneaky search, leaving regular `/` alone.  This would use its own highlight instead of `hlsearch`, and jump with `SneakNext` and `SneakPrevious`.  Bonus if it can still use `incsearch` as the pattern is being typed.

Thoughts?

**Comment by justinmk** [comment]
The intended theme of sneak.vim (and any of my plugins in general) is not to replace any part of Vim but to [complement it](https://github.com/justinmk/vim-sneak#motivationhttps://github.com/justinmk/vim-sneak#motivation) or fill a real gap. 

`/` with `incsearch` serves its purpose very well, and wrapping it with sneak's behavior IMO is a mistake. In particular, label-mode ("streak" mode) don't make sense with incsearch: if you're entering a pattern, the keystrokes saved by on-screen matches are negligible at that point.

https://github.com/easymotion/vim-easymotion makes all these mistakes anyway, so it's available for people who want that.

Note that a similar discussion is at https://github.com/justinmk/vim-sneak/issues/104 and I plan to enable the functionality discussed there, though it's stalled at the moment.

**Comment by cuviper** [comment]
OK, thanks for considering it.  I'll keep an eye on that other discussion.

**Comment by justinmk** [comment]
> Sometimes it is nice to have hlsearch shown, which is why I enable it at all, but often I only want to get to the right location and clear the highlight.

I strongly recommend [this sensible.vim mapping](https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim#L33) if you aren't already using it:

    nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>

Just mash `<C-L>` whenever you want to clear incsearch.

**Comment by cuviper** [comment]
Yep, I do use `<C-L>`!  Actually, it might be a nice way to clear sneak highlights too, without waiting for movement.  I suppose I can just add `call sneak#hl#removehl()`?

**Comment by justinmk** [comment]
> Actually, it might be a nice way to clear sneak highlights too, without waiting for movement.

Sure, or `<Esc>` works [by default](https://github.com/justinmk/vim-sneak/blob/master/plugin/sneak.vim#L204) if you are running GUI Vim or Neovim (terminal and GUI), and don't already have it mapped.
