### ISSUE TITLE
Ignore accents

### ISSUE THREAD

**Issue by danielbmarques** [justinmk/vim-sneak#173]
I don't know how hard it would be to do this, but it would be really _really_ great if Sneak could consider characters with or without accents as the same.
Just now I wanted to go to the word "ética", for instance, and I instinctively tried Sneak with `et`, but it doesn't work. This happens to me all the time.

PS: I love Sneak, thanks for making it!

**Comment by justinmk** [comment]
I think this is what `:lnoremap` is for. Let's merge this with https://github.com/justinmk/vim-sneak/issues/138

If you really like this kind of thing, easymotion probably has a feature for it already, I think. The goal of sneak is less "do what I mean" (DWIM) and more narrow.

Thanks too :)

**Comment by danielbmarques** [comment]
I've tried easymotion, but I don't like it as much. :/

`lmap` is just like a regular mapping but for more than one mode, isn't it? Maybe I'm missing something, but I don't see how that's relevant.
What I want in my example is that Sneak `et` would match not only "ét", but both "et" and "ét".

Here I mapped `f` to use one-character Sneak and did `fo`:

![sneak](https://cloud.githubusercontent.com/assets/15813674/15789077/d95386d6-29a0-11e6-9b06-bdc36dc537c8.png)

Here I'd hope "õ" and "ô" to be highlighted too.

I think what we would need is something like this: http://vi.stackexchange.com/a/7394

Searching for `[[=e=]]` matches "e", "é", "ê" and so on. So we'd need an option that would cause Sneak to search for `[[=e=]]` when you type `e`, `[[=a=]]` when you type `a` etc. I don't see any drawbacks in doing this (except perhaps for the performance of the plugin), but it could be changed with an option anyway.

I don't use `lmap` or `keymap`, I use [combining characters](https://en.wikipedia.org/wiki/Combining_character) for accents, so to type "ética" I actually type `'etica`. Sneak doesn't count `'e` as "é", though, so I can't search for that character at all, and the same goes for all accented characters. Using collection classes would fix that and many other possible problems IMHO, making Sneak a lot more flexible.

**Comment by justinmk** [comment]
Hmm, equivalence class looks useful. It shouldn't be much code to support this so I'll keep it open.

**Comment by danielbmarques** [comment]
Great, thanks! 🎉

**Comment by danielbmarques** [comment]
I can try to implement this if you want, but I don't know much about Vimscript, so I'd need some help.

Now I just looked into your `search.vim` and tried replacing the line that says
```vim
    let self.search = escape(a:input, '"\')
```

with

```vim
    let self.search = substitute(a:input, '\a', '[[=\0=]]', 'g')
```

But it doesn't work, I don't know why. Doing that never get any matches anymore.

**Comment by justinmk** [comment]
Sorry, it might be awhile before I can help with this.

**Comment by danielbmarques** [comment]
No problem, I'll keep trying and I'll post here if I get anywhere, and you can look into it whenever you have the time. Thanks again. :)

**Comment by danielbmarques** [comment]
Aha! I think I got it.

The problem was the escaping, and the I tried to escape just the characters in the original code, `"\`, but it wasn't working.

Besides escaping those characters, now I tried adding a backslash before the whole equivalence class too:

```vim
    let escapedstring = escape(a:input, '"\')
    let self.search = substitute(escapedstring, '\a', '\\[[=\0=]]', 'g')
```

And it works! Here's `sae`:

![captura de tela 2016-06-03 as 18 09 39](https://cloud.githubusercontent.com/assets/15813674/15793139/6813ffe2-29b8-11e6-847e-02d702260fab.png)

I also tried some other random characters, slashes, quotes, braces, it seems like it's all working as it should.

I didn't make a PR already because I don't know if this has any unintended consequences or if there's something else we'd have to change too, I got to this via wild guesses and I'm not familiar with the rest of the code at all. But if you think it's alright I can make a PR too.

For now I'll keep using it like this and if anything weird shows up I'll let you know.

**Comment by justinmk** [comment]
Nice! Try it for a few days and let me know. This is simple enough that it's worth adding.

**Comment by danielbmarques** [comment]
Ok, I used this a lot over the last month and it seems to be working great. :)
I still don't know why it needed that extra back slash, but it works perfectly and it made sneak a hundred times better for me.
Should I make a PR or something?

**Comment by justinmk** [comment]
@danielbmarques PR would be welcome.

**Comment by ggandor** [comment]
In case someone is reading this now and interested: the extra backslash at the beginning of `'\\[[=\0=]]'` is necessary because the final search pattern is very nomagic (`self.prefix` sets `\V`), but we need a collection-delimiting pair of brackets (`\[]`) around the equivalence class, not literal ones.
