### ISSUE TITLE
Does not restore StatusLine link

### ISSUE THREAD

**Issue by blueyed** [justinmk/vim-sneak#174]
I have the following StatusLine highlighting:

```vim
:hi StatusLine
StatusLine     xxx cterm=reverse ctermfg=19 ctermbg=21 gui=bold,reverse
                   links to DiffChange
```

Sneak links this to its own group, but when restoring it only removes its own link.
Therefore I end up with just `StatusLine     xxx cterm=reverse ctermfg=19 ctermbg=21 gui=bold,reverse` (without the link).
(It comes from `colorscheme-solarized/colors/solarized.vim`)

IIRC you have some other plugin that handles this properly already?!
Otherwise I can look for it.

**Comment by justinmk** [comment]
I was actually planning to remove the status line highlight completely. I don't think anyone will miss it.

**Comment by blueyed** [comment]
Good idea, thanks!
