### ISSUE TITLE
Incorrect behaviour in operator-pending mode when query does not exists

### ISSUE THREAD

**Issue by HarmtH** [justinmk/vim-sneak#177]
When using t- or f-like sneaking in operator-pending mode, and the query does not exists, the operator gets applied on the current character

**Comment by tuurep** [comment]
This is still an issue when using the operator-pending `v` (this concerns any Sneak motion with any parameters):

Given `abcdef`

- `dvzxy` => `bcdef`
- `dvz<Esc>` => `bcdef`

What I've found is that it happens even with a plain `searchpos()` like this:

```lua
-- Dummy sneaklike motion
vim.keymap.set({"n", "x", "o"}, "<M-s>", function()
    vim.fn.searchpos("xy") -- No match in "abcdef"
end)
```

- `dv<M-s>` => `bcdef`

Even when `searchpos()` is used with the `"n"` flag ("do Not move the cursor"), it still happens with the operator-pending `v`

```lua
    vim.fn.searchpos("xy", "n")
```

Therefore finding it really tricky to find a fix for it :/

I suppose it's like this: by using `searchpos()`, it at least does a zero-width jump, and the `v` flag turns that `inclusive`? What's needed instead is to cancel the whole operator.
