### ISSUE TITLE
Incorrect behaviour when exclusive (t-like) sneaking in visual mode

### ISSUE THREAD

**Issue by HarmtH** [justinmk/vim-sneak#179]
When using the repeat command while t-like sneaking in visual mode, and there is no more next result, the character you search for gets included in the visual selection.

**Comment by nkgm** [comment]
@HarmtH is this still an issue for you? I'm having a similar "minus one char" problem with `Sneak_{f,t}` when `set selection=exclusive` in visual mode (initial selection and repeat alike). @justinmk ideas?
