### ISSUE TITLE
`<Plug>Sneak_f` and friends clobber the ' mark even if they don't change lines

### ISSUE THREAD

**Issue by dmwit** [justinmk/vim-sneak#185]
I like the sneak variants of `fFtT` because they are multiline. However, unlike the builtin `fFtT`, sneak always resets the `'` mark. This means if I jump to the top of the file, use `fx` to get to the `x` character that appears on the first line of the file, then `''` to get back to where I was, I don't go back where I was. Annoying!

I can see why you would want to set the mark when changing lines; but when behaving like the builtin commands (and not changing lines), I think it should not change the existing mark.

**Comment by justinmk** [comment]
I sometimes find it useful, but I suppose it's worth a try.

**Comment by justinmk** [comment]
Historically, adding "smart" behavior like this would entail, ends up being to unpredictable. The inconsistent behavior is a tradeoff, it's not a clear benefit. Sometimes it's useful, sometimes not. In such a case, where the benefit is a "wash", it's better to be consistent. 

In the scenario you describe, just use `<c-o><c-o>` to go back.
