### ISSUE TITLE
Streak closes folds with foldmethod=syntax

### ISSUE THREAD

**Issue by hardenedapple** [justinmk/vim-sneak#186]
The trick of turning syntax off and back on used to avoid keyword syntax highlighting overriding the markers means that if `foldmethod=syntax` the folds are recalculated and closed after the motion. This also means that during the streak all folds are opened instead of just looking over the unfolded text.

This is troublesome for motions during an operation, as they then act on the entire fold.

I've found that setting  `foldmethod=manual` just before turning syntax off in `s:before()`, then resetting it in `s:after()` as seen in the patch below appears to stop these problems.
You could put an if clause around `set foldmethod=manual` so it's only done if the foldmethod was originally `syntax` if you want -- I don't know if that's better or not.

```patch
diff --git a/autoload/sneak/streak.vim b/autoload/sneak/streak.vim
index 3ffb5af..31756e4 100644
--- a/autoload/sneak/streak.vim
+++ b/autoload/sneak/streak.vim
@@ -107,6 +107,7 @@ func! s:after()
   exec 'hi! link Conceal '.s:orig_hl_conceal
   exec 'hi! link SneakPluginTarget '.s:orig_hl_sneaktarget
   let &synmaxcol=s:synmaxcol_orig
+  silent! let &foldmethod=s:foldmethod_orig
   silent! let &syntax=s:syntax_orig
   let &concealcursor=s:cc_orig
   let &conceallevel=s:cl_orig
@@ -141,6 +142,8 @@ func! s:before()
   let s:cc_orig=&l:concealcursor | setlocal concealcursor=ncv
   let s:cl_orig=&l:conceallevel  | setlocal conceallevel=2
 
+  let s:foldmethod_orig=&foldmethod
+  let &foldmethod='manual'
   let s:syntax_orig=&syntax
   syntax clear
   " this is fast since we cleared syntax, and it allows sneak to work on very long wrapped lines.
```

EDIT
Just thought I'd mention -- I've raised an issue instead of a pull request because I suspect there's a better solution out there.

**Comment by justinmk** [comment]
@hardenedapple Thanks for reporting, and suggesting a solution! I think your solution is about as good as it gets.
