### ISSUE TITLE
Variable Streak?

### ISSUE THREAD

**Issue by matrinox** [justinmk/vim-sneak#187]
Is is possible to set a number of characters before it starts to search? 2 is good but I feel 3 is more reliable for me. I can think less of what characters to use and it's way more accurate with that third letter

**Comment by justinmk** [comment]
Yes, it's supported, there's even test coverage for this IIRC. There might be an example in the doc, else ping me tomorrow and I'll dig up some mappings.

**Comment by matrinox** [comment]
I see, you have to something like this:
```vim
nnoremap <silent>s <Plug>Sneak_f :<c-u>call sneak#wrap('', 3, 0, 1, 0)<cr>
nnoremap <silent>S <Plug>Sneak_f :<c-u>call sneak#wrap('', 3, 1, 1, 0)<cr>
```

**Comment by matrinox** [comment]
doesn't work for me, do you mind digging that up for me? Much appreciated

**Comment by justinmk** [comment]
Added these examples to the help doc:

      "Example: Configure "f" to trigger label-mode: >
        nnoremap <silent> f :<C-U>call sneak#wrap('',           1, 0, 1, 1)<CR>
        nnoremap <silent> F :<C-U>call sneak#wrap('',           1, 1, 1, 1)<CR>
        xnoremap <silent> f :<C-U>call sneak#wrap(visualmode(), 1, 0, 1, 1)<CR>
        xnoremap <silent> F :<C-U>call sneak#wrap(visualmode(), 1, 1, 1, 1)<CR>
        onoremap <silent> f :<C-U>call sneak#wrap(v:operator,   1, 0, 1, 1)<CR>
        onoremap <silent> F :<C-U>call sneak#wrap(v:operator,   1, 1, 1, 1)<CR>

      "Example: Configure "s" to wait for 3 characters: >
        nnoremap <silent> s :<C-U>call sneak#wrap('',           3, 0, 2, 1)<CR>
        nnoremap <silent> S :<C-U>call sneak#wrap('',           3, 1, 2, 1)<CR>
        xnoremap <silent> s :<C-U>call sneak#wrap(visualmode(), 3, 0, 2, 1)<CR>
        xnoremap <silent> S :<C-U>call sneak#wrap(visualmode(), 3, 1, 2, 1)<CR>
        onoremap <silent> s :<C-U>call sneak#wrap(v:operator,   3, 0, 2, 1)<CR>
        onoremap <silent> S :<C-U>call sneak#wrap(v:operator,   3, 1, 2, 1)<CR>

**Comment by matrinox** [comment]
thanks!
