### ISSUE TITLE
How to change color?

### ISSUE THREAD

**Issue by matrinox** [justinmk/vim-sneak#188]
I've added the following:

```vim
autocmd ColorScheme * hi Sneak guifg=black guibg=red ctermfg=black ctermbg=red
autocmd ColorScheme * hi SneakScope guifg=red guibg=yellow ctermfg=red ctermbg=yellow
autocmd ColorScheme * hi SneakLabel guifg=white guibg=magenta ctermfg=white ctermbg=gree
```

No colour seems to change (still magenta). Am I doing something wrong?

**Comment by justinmk** [comment]
That works for me. Are you doing that before calling `:colorscheme`?

I may need to give up and add an option for this :<

**Comment by matrinox** [comment]
oh I see, I have to call it before.

Other plugins use highlight, why not just use that? It's easier to test colours out rapidly in command mode.

**Comment by justinmk** [comment]
> Other plugins use highlight, why not just use that? 

I don't know what you mean. Sneak uses `:highlight`. Any `:highlight` you do in your vimrc will be cleared by a call to `:colorscheme`. That's a Vim problem, nothing I can do about it. But that's the reason handling the ColorScheme event is necessary: to re-apply the `:highlight` whenever `:colorscheme` is called (by your vimrc or whatever).

The only way I'm aware of, for a plugin to avoid the problem above, is to accept some custom variable like `g:foo` which is re-applied by the plugin for you.

**Comment by dbmrq** [comment]
I'm probably doing something stupid, but I can't get it to work either. I tried adding `autocmd ColorScheme * hi link Sneak Search` before and after calling `:colorscheme`. I also did `autocmd ColorScheme * echom "whatever"` right after and I get "whatever" at my `:messages`, but the color is still the hideous magenta. Before, when I used `hi link SneakPluginTarget Search`, it worked fine. I don't know what's wrong now.

**Comment by justinmk** [comment]
@dbmrq Try `hi! link Sneak Search` (notice the "!"). If that doesn't work, can you confirm whether this works if you enter it manually at the vim command prompt:

    hi! link Sneak Search

**Comment by dbmrq** [comment]
@justinmk Oops… that wasn't working too, so I cloned the latest commit again and now it all works. I was sure I had the latest version already, but apparently not, sorry. Thanks for your help!

**Comment by justinmk** [comment]
@dbmrq Thanks. I guess this can be closed. Specific requests are welcome.

**Comment by matrinox** [comment]
Sorry to comment on a closed issue. I'm quite new to vim so I don't understand the intricacies of the colour system. What I do know is that easy motion, for example, allows you to customize their stuff on the fly. I can call `hi EasyMotionIncSearch ...` and the colour changes. But when I do that with sneak, nothing changes. That's what I meant in my earlier comment
