### ISSUE TITLE
error when moving past last item

### ISSUE THREAD

**Issue by nhooyr** [justinmk/vim-sneak#191]
1. Open vim
2. Type some newlines and put `foo` somwhere in between
3. Go to the top
4. Search for `fo` with sneak
5. Try to go to the next one
6. Error instead of silently doing nothing

Also, watch: https://asciinema.org/a/b6x9mq0ik4izpb83yx51vrb24

The full error is:

```
Error detected while processing function sneak#wrap[8]..sneak#to[118]..sneak#label#to[3]..<SNR>100_do_label:
line   48:
E716: Key not present in Dictionary: a
E15: Invalid expression: mappedtoNext ? s:matchmap[strpart(g:sneak#target_labels, 0, 1)] : s:matchmap[choice]
```

**Comment by justinmk** [comment]
Heh. I made a note of this bug a long time ago: https://github.com/justinmk/vim-sneak/commit/628f9d0e2d88b4b440b6b2e0e74d0f48e86eec55#diff-2336eb3ad7b84c249dc9b75108450e55R43

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.

**Comment by dseeni** [comment]
I'm still experiencing this in the latest version of NVIM v0.5.0-417-g5a5c2f029
running on Windows with Nvim-Qt
