### ISSUE TITLE
Feature Request: Symbol Groups (characters matching a group of characters.)

### ISSUE THREAD

**Issue by yzhuang** [justinmk/vim-sneak#192]
E.g. It would be nice to be able to define character "[" to match any of "[", "(", "<", or "{", so that when "sa[" is typed, it match "a(" or "a[" or "a{" or "a<".

This feature is available in vim-sneak clones, e.g. evil-snipe, but doesn't seem to be available in vim-sneak itself.  

Having this functionality in vim-sneak would be nice. Personally, I find it very helpful to define ";" to match all punctuations / symbols.  So "sf;" can match all the the following cases, and ";" is much easier to type than "~" or "=" or "(" and so on.

```
int f[10]
public void f() { ... }
f++
<a href=...>
```

**Comment by justinmk** [comment]
In all of those cases I would do `s<space>f` instead of `sf<punctuation>`. 

However one could use a [autocmd](https://github.com/justinmk/vim-sneak/issues/128) to setup temporary mappings or abbreviations. 

So, supporting this only needs the autocmd. The rest is standard Vim functionality.
