### ISSUE TITLE
Question: Is it possible to pass vim-sneak parameter to easymotion?

### ISSUE THREAD

**Issue by rawaludin** [justinmk/vim-sneak#194]
When I'm searching for some string and found too many matches, sometimes I changed my vim-sneak and use easymotion instead. My reasoning for this is pressing `;` or `,` more than 10x is tedious. I don't like counting too to get to my match.

Is it possible to pass my vim-sneak parameter and trigger easymotion?
Let say, I press `s{char}{char}` to activate vim sneak, and found too many matches, then press `<Leader>;` then exit vim-sneak and trigger easymotion with vim-sneak parameter.

Thanks.

**Comment by justinmk** [comment]
Label-mode is like easy motion.
