### ISSUE TITLE
How to use lowercase s to sneak over entire visible screen?

### ISSUE THREAD

**Issue by Asheq** [justinmk/vim-sneak#196]
I LOVE the idea of this plugin. I use label mode, but it's slightly cumbersome to use capital `S` to sneak backwards.

I would like to use just lowercase `s` to sneak to anything on the screen, even if it's above/behind the cursor. For two reasons:

- Less cognitive friction, i.e., my brain doesn't have to think about where the cursor is relative to the target
- Less key-presses, i.e., I don't ever have to press the Shift key

My tentative solution is to just jump to the top of the screen with `H` first. I setup the following maps

    nmap s H<Plug>Sneak_s
    xmap s H<Plug>Sneak_s

One problem with this is that it pollutes my jump-list with that intermediary jump to the top of the screen, using `H`.

Is there a better solution? Some sort of built-in option?

Thanks!

**Comment by justinmk** [comment]
@Asheq Thanks. 

> My tentative solution is to just jump to the top of the screen with H firs

That's the usual workaround, but it does have problems. The real solution would be bi-directional search, but I think this is a feature people think they want but then after using it will likely change their minds. See also the discussion at https://github.com/justinmk/vim-sneak/issues/62#issuecomment-281489165

> Less cognitive friction, i.e., my brain doesn't have to think about where the cursor is relative to the target

By always labeling things in both directions it _adds_ cognitive friction, because it means label-mode is always invoked. Label-mode itself is a compromise.

**Comment by Asheq** [comment]
Thanks for the quick response @justinmk!

I am relatively new to sneak, so I think I owe the default uni-directional search a chance to win me over. I understand that the disadvantage of my desired behavior is that label-mode would be invoked more often.

However, to play devil's advocate, there is a possibility that label-mode is invoked a large percentage of the time (~90%) anyway. This would be the case for someone who keeps his or her font tiny, has crowded buffer contents, and tends to search for common letters. Even the default uni-directional behavior wouldn't help in limiting the amount of time label-mode is invoked. Why not give that person the simplicity of always pressing `s`?

At any rate, I do appreciate the simplicity/speed of this plugin, over a more bloated solution that tries to make absolutely everyone happy.

**Comment by justinmk** [comment]
There are other reasons: https://github.com/justinmk/vim-sneak/issues/62#issuecomment-281700340

However the ability to [switch direction](https://github.com/justinmk/vim-sneak/issues/62#issuecomment-281701395) might be a good tradeoff. And there's always easymotion :)
