### ISSUE TITLE
Label mode causes IndentLine characters to disappear

### ISSUE THREAD

**Issue by talw** [justinmk/vim-sneak#198]
Hi!

I'm using [IndentLine](https://github.com/Yggdroot/indentLine) to display line characters where there are spaces to show indentation.

If I use sneak's label mode, all those line characters disappear, and I can only restore them by doing things like executing `:e` or `:IndentLinesToggle` twice.

I assume this has to do with conceal? Seeing as how both IndentLine and Sneak use it.
There are 2 closed issues with the combination of these 2 plugins but none of them are related to this issue.

**Comment by justinmk** [comment]
Yeah, seems like indentLine isn't getting re-enabled after temporarily disabling syntax. indentLine should listen to the Syntax autocmd. Other than that, not much can be done.

**Comment by talw** [comment]
Thanks for the diagnosis.
I'll an open an issue for IndentLine then.

**Comment by bluz71** [comment]
@talw,

As a brand new 'sneak' user myself this issue immediately effected me.

Luckily there appears to be a very easy fix.

Just add the following to your ~/.vimrc

  `autocmd Syntax * IndentLinesReset`

@justinmk,

You are correct to close this issue, the IndentLine plugin is at fault.

Maybe add the solution to your FAQ / Trouble-Shooting documentation for future users (who also use IndentLine)?

**Comment by talw** [comment]
@bluz71, it worked like a charm, thanks!

So I understand that 'autocmd Syntax' is for running commands when the syntax highlighting changes, nice! I feel like I should've come across it, but things time has passed since I looked into this issue I do not remember what things I've tried.
