### ISSUE TITLE
Bind localleader in netrw?

### ISSUE THREAD

**Issue by lunaryorn** [justinmk/vim-sneak#199]
With the default `g:sneak#map_netrw = 1` sneak "moves" `s` in netrw to `<leader>s`, but I wonder whether that shouldn't be `<localleader>s`?  Pardon me if I'm asking a stupid question, I'm not too familiar with Vim's idioms for bindings and may have misunderstood the meaning of `<localleader>`.

That said, I have a lot of own leader bindings, including one on `s` which I'd hate to loose in netrw.  Would it be possible to add an option to change the key where vim-sneak moves the `s` binding of netrw?

**Comment by justinmk** [comment]
> Would it be possible to add an option to change the key where vim-sneak moves the s binding of netrw?

Would that be much different than `g:sneak#map_netrw=0` combined with:

```vim
augroup vimrc_stuff
au!
au FileType netrw * nmap <buffer> <localleader>s <Plug>Sneak_s
augroup END
```

Assuming "FileType netrw" actually works. Doesn't seem to for me. Maybe another netrw bug. 

I guess changing `g:sneak#map_netrw` to be a string instead of a boolean wouldn't be a problem.

**Comment by justinmk** [comment]
I was also considering removing `g:sneak#map_netrw` entirely...
