### ISSUE TITLE
High position shortcut labels are not displayed.

### ISSUE THREAD

**Issue by vbauerster** [justinmk/vim-sneak#204]
When invoking vim-sneak form the very bottom of window, high position labels are not displayed:

[![Screen Shot 2017-06-23 at 13.14.38.png](https://s25.postimg.org/dhehmfb9r/Screen_Shot_2017-06-23_at_13.14.38.png)](https://postimg.org/image/bcu4lc9mz/)

I'm using [gruvbox](https://github.com/morhetz/gruvbox) colorscheme.

**Comment by justinmk** [comment]
Use tab to label the next set. Or backspace to go the other way.
