### ISSUE TITLE
sneak#is_sneaking() returns 1 when matches are not highlighted

### ISSUE THREAD

**Issue by dahlbaek** [justinmk/vim-sneak#206]
First of all, thank you for this awesome plugin!

I found what I believe to be a small bug. Using the setting `let g:sneak#label = 1`, I find that after sneaking with `s{char}{char};`, the command `:echom sneak#is_sneaking()` returns `1`, even though nothing is highlighted.

In my own setup (where I do not use `let g:sneak#label = 1`), this means that the keys s and S behave unintuitively, since I am using the settings
```
nmap <silent> <expr> s sneak#is_sneaking() ? '<Plug>SneakLabel_s<cr>' : '<Plug>Sneak_s'
nmap <silent> <expr> S sneak#is_sneaking() ? '<Plug>SneakLabel_S<cr>' : '<Plug>Sneak_S'
let g:sneak#target_labels=';qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM'
```

**Comment by justinmk** [comment]
I don't see that issue. Can you reproduce it with only sneak enabled? Like this:

    vim -u NORC -N +":set runtimepath+=~/path/to/vim-sneak/" +":runtime plugin/sneak.vim"

what are the exact steps after that?

**Comment by dahlbaek** [comment]
First open vim with the command (note the nmap at the end)
```
vim -u NORC -N +":set runtimepath+=~/path/to/vim-sneak" +":runtime plugin/sneak.vim" +":nmap s <Plug>SneakLabel_s"
```
For me, this opens Vim 8.0.95.

Then press `iaaaaaa<esc>0saa;`. This should have the effects:
1) `iaaaaaa<esc>0`: Write the line `aaaaaa` and move the cursor to the beginning of the line in normal mode.
2) `saa`: fire up sneak in label mode and move the cursor to the first hit (which will be the third `a`).
3) `;`: Select the next hit (which will be the fifth `a`).

At this point, nothing is highlighted. Now enter `:echom sneak#is_sneaking()`. When I do this, it returns `1`, even though nothing is highlighted. This behaviour is the same in Neovim 0.1.7 for me.

Also, in Vim, pressing `<esc>` at this point has no effect. This appears to be different in Neovim 0.1.7: Here, pressing `<esc>` causes `:echom sneak#is_sneaking()` to return `0`.

**Comment by dahlbaek** [comment]
So, I do not really have any experience with this kind of stuff, so I do not know if this suggestion is completely off the mark. But I edited the /path/to/vim-sneak//plugin/sneak.vim in the following two places:
line 172: `  call sneak#hl#removehl()` changed to `  call sneak#cancel()`.
line 214: `    call sneak#hl#removehl()` changed to `    call sneak#cancel()`.
After this change, sneak#is_sneaking() seems to behave in the way I would expect.

**Comment by dahlbaek** [comment]
The situation also seems to affect the 1-character enhanced sneaks, if they are used in operator-pending mode. The 'fix' I propose above seems to apply in this case as well. If you do not mind, and if you think that the 'fix' is appropriate, I can test it for some weeks and create a PR. Of course, I am not really that familiar with vim-sneak or vimscript in general, so maybe you can already tell that the 'fix' is inappropriate and/or breaks some other functionality.

**Comment by dahlbaek** [comment]
After trying this out for a bit, I think that vim-sneak is already working as intended. Instead of making any changes to the functionality of vim-sneak, I propose to make a small change to the documentiation of the `sneak#is_sneaking()` function. Of course, you may disagree and think that the current description is already accurate. In that case i apologize for the inconvenience!
