### ISSUE TITLE
label-mode works with MacVim but not terminal vim

### ISSUE THREAD

**Issue by sarkologist** [justinmk/vim-sneak#209]
With `let g:sneak#label = 1` hitting `s` does use label-mode in MacVim (8.0.1175) but not in terminal vim.

By terminal vim I mean
```
$ ls -al $(which vim)
lrwxr-xr-x  1 sark  admin  30  7 Oct 14:46 /usr/local/bin/vim -> ../Cellar/vim/8.0.1175/bin/vim
```

If I force `nmap s <Plug>SneakLabel_s`, then it does _seem_ to use label-mode, but then the colors are such that I cannot see the labels, or even the original text!

This doesn't seem to be a problem with my themes as I get the same behaviour when I switch them.

**Comment by justinmk** [comment]
Sounds like a Vim regression. Does it happen with older versions?

**Comment by sarkologist** [comment]
Looks like you are correct. With `brew install vim@7.4` it works fine.

**Comment by sarkologist** [comment]
Sorry I may have been confused there.

When it did not work, I had:
```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
Included patches: 1-898, 8056
Compiled by root@apple.com
...
```

Now it works with:
```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  5 2017 19:19:02)
MacOS X (unix) version
Included patches: 1-1175
Compiled by Homebrew
...
```
