### ISSUE TITLE
Feature request: custom mappings to escape prompt

### ISSUE THREAD

**Issue by auwsmit** [justinmk/vim-sneak#215]
I have personally mapped `<c-g>` to act like `<esc>` in nearly every context, just to have more parity with Emacs, but I'm not sure how to configure sneak to have a custom prompt-exiting map.

Is this possible with a snippet, or could it be implemented as a new option?

**Comment by justinmk** [comment]
Out of scope to add more customization, but CTRL-g is common enough, so it cancels the prompt by default now.
