### ISSUE TITLE
Showing location of the first jump (where the cursor has already moved)

### ISSUE THREAD

**Issue by rococode** [justinmk/vim-sneak#216]
Is there any way to also highlight where the cursor has already moved to? (and just not show a label there, if labels are on).

It would be nice to be able to have some instant feedback when a jump happens, instead of having to move the cursor before actually seeing where the cursor jumped to.

**Comment by justinmk** [comment]
This should already work. It uses the highlight defined by `Cursor`. Check

    :hi Cursor

to see how your colorscheme defined `Cursor`.

Try a different colorscheme, if it works there, fix the other colorscheme.
