### ISSUE TITLE
Switch role for Sneak_; Sneak_, for Sneak_F, Sneak_S

### ISSUE THREAD

**Issue by ipod825** [justinmk/vim-sneak#217]
Is it possible to switch the role of Sneak_; and Sneak_,  for Sneak_F, Sneak_S.
Motivation is I have such mapping:
nmap f <Plug>Sneak_f
nmap F <Plug>Sneak_F
nmap H <Plug>Sneak_,
nmap L <Plug>Sneak_;

It makes more sense to jump back when I press H. But if I type F at the beginning, it will lead me forward.

**Comment by justinmk** [comment]
I don't know what you're asking, but try `g:sneak#absolute_dir = 1`

**Comment by ipod825** [comment]
Thanks, exactly what I am looking for.
