### ISSUE TITLE
Label mode doesn't work when there are exactly 2 matches

### ISSUE THREAD

**Issue by joshuazd** [justinmk/vim-sneak#220]
When label mode is turned on, labels are not shown when there are exactly two matches.  Instead, it works as if label mode were off.

In line 205 of [plugin/sneak.vim](https://github.com/justinmk/vim-sneak/blob/master/plugin/sneak.vim#L205), changing s.hasmatches(2) to s.hasmatches(1) seems to solve the problem.  I'm not sure, but this may have to do with finding a match at the cursor position.

**Comment by justinmk** [comment]
It's intentional. If there are 2 matches then the "labeled" match would always be `;` (or whatever you mapped to `<Plug>Sneak_;`.
