### ISSUE TITLE
Highlighting cursor at first occurrence of Sneak_s

### ISSUE THREAD

**Issue by silvioricardoc** [justinmk/vim-sneak#221]
Hi, there,

I love your plugin.

I was wondering if there is a way highlighting the match under the cursor when it is on top of the first occurrence of something. The `Sneak` highlight group works for all other occurrences, but the one under the cursor is not highlighted by default.

(I'm using `Sneak_f` and `Sneak_s`, which do not require a keypress for the first position. When running `SneakStreak`, all cases do get highlighted, including the first, labeled ";").

I have looked into the source code, but I don't see a highlight group that corresponds to what I want. Is this implemented (or are there plans of implementing it?)

Thanks!

**Comment by justinmk** [comment]
The highlight group is builtin: `Cursor`. What does `:hi Cursor` show ?

**Comment by silvioricardoc** [comment]
I have `gui=reverse` for the cursor. I was hoping for a way of highlighting the whole match (two characters instead of one for `Sneak_s`, and the second one should not blink, as the cursor is not over it).

**Comment by justinmk** [comment]
Are you using a gui? If not, `gui=reverse` won't do anything.  

> I was hoping for a way of highlighting the whole match (two characters instead of one for Sneak_s, and the second one should not blink, as the cursor is not over it).

So the cursor appears, but it does not appear in this very specific way that you expect?

**Comment by silvioricardoc** [comment]
The problem is not that I don't see the cursor. I do see the cursor, but I don't see the *match* right under it. (This happens both on the terminal vim and on GVim).

For example, consider this image:
![sneak-not-highlighted-example](https://user-images.githubusercontent.com/8845301/36670397-7929d4fe-1af8-11e8-831d-78b7c72d3fd4.png)

I created it by typing `s` and then `xa` on the first line. I expected *all* matches to be highlighted, but the current one under the cursor is not. (Compare this to `set hlsearch`, which shows even the first match for the `/` mapping).

Is there a way of having all three occurrences of `xa` highlighted?

**Comment by justinmk** [comment]
> I do see the cursor, but I don't see the match right under it.

That's intentional. The cursor is already "there".

> Is there a way of having all three occurrences of xa highlighted?

Map to `<Plug>SneakLabel_s` (legacy name: `<Plug>SneakStreak`) directly. Otherwise, no.
