### ISSUE TITLE
Label mode highlight symbols break concealed characters in other windows

### ISSUE THREAD

**Issue by kutsan** [justinmk/vim-sneak#222]
So, in summary:

My configuration is [here](https://github.com/kutsan/dotfiles/blob/199a299786872e35e9647099fe2bdabb57e36784/.vim/package/sneak.vim).

![](https://i.imgur.com/w7EpwVM.gif)

**Comment by justinmk** [comment]
Welcome to Vim. There's nothing that can be done about this.

**Comment by kutsan** [comment]
Why, care to explain? Isn't `conceallevel` option buffer-only, I thought it wasn't global?

**Comment by justinmk** [comment]
`conceallevel` is window-local, but `Conceal` highlight group is not.

Explained in e990c66137dfe158964e58ebbf752afcfae000ea.

**Comment by kutsan** [comment]
Is this only for indentLine plugin? Because when I comment out these lines, it works okay. I just don't want to see those concealed characters in nerdtree and I don't use indentLine.

https://github.com/justinmk/vim-sneak/blob/1b02940ee4513575b2c3e44306ca945be685a7ce/autoload/sneak/label.vim#L169

https://github.com/justinmk/vim-sneak/blob/1b02940ee4513575b2c3e44306ca945be685a7ce/autoload/sneak/label.vim#L117

**Comment by justinmk** [comment]
It might work by accident for you, until you use another plugin which also uses Conceal. I suppose we could do some sort of sanity check to detect whether Conceal was modified, then skip the disable/restore dance if not.

**Comment by kutsan** [comment]
Well, I only commented out those lines and I'm using like that for 30-40 minutes so, haven't had any problem since then. I don't actually use many plugins, I think sneak is the only plugin which modifies the Conceal. Sanity checks would be awesome.

**Comment by justinmk** [comment]
@kutsan I was wrong. With c2cbcf789839d6d9f39a55b142479dcbc5a082f9 and Vim 7.4.792 or Nvim 0.2, since `matchadd()` is used now, `s:disable_conceal_in_other_windows()` is not needed anymore. Thanks for pushing back on this :)

**Comment by kutsan** [comment]
THANK YOU SO MUCH! Now it works flawlessly.
