### ISSUE TITLE
"Sneak enters label-mode if there are ≥2 visible (on-screen) matches." - Why?

### ISSUE THREAD

**Issue by superDuperCyberTechno** [justinmk/vim-sneak#225]
I find myself wanting to go to the second of 2 available results but this specific feature/design choice makes it really cumbersome when I'm used to this wonderful plugin...

Any reason for this? Any way to change it to label mode on simply more than 1 result?

This is my current sneak configuration:
```
let g:sneak#target_labels = "ertyuisdfghjklcvbnm"
let g:sneak#use_ic_scs = 1
let g:sneak#label = 1
map f H<Plug>Sneak_s
map F H<Plug>Sneak_S
```

**Comment by superDuperCyberTechno** [comment]
Well, cumbersome seems a little extreme. Anyway, as I'm used to feed sneak a displayed label, it's a little confusing when the result I want to go to doesn't get one. Does that make any sense?

**Comment by justinmk** [comment]
The displayed label for the first match is always `;` (or whatever is mapped to `<Plug>Sneak_;`).

But now that the "shading" doesn't happen I guess there's no reason not to show the labels.
