### ISSUE TITLE
S just deletes 1 character?

### ISSUE THREAD

**Issue by 9mm** [justinmk/vim-sneak#229]
Dumb question, but how do I actually enable it? When I use vundle to install it, I can't seem to actually trigger it with `s`

**Comment by justinmk** [comment]
It should work after being installed. Did you restart vim after installing? Is sneak listed in `:scriptnames` ? 

Try asking on https://github.com/VundleVim/Vundle.vim or https://vi.stackexchange.com/

**Comment by 9mm** [comment]
Yes it's listed in `:scriptnames` (`plugin/sneak.vim`)

And all my other plugins are working, and have been for years, I don't think it's a vundle issue.

Is there a way I can check if another plugin is overriding 's' somehow?

**Comment by 9mm** [comment]
Or to see if any sneak command/functions are avilable if I do :sn...<tab> maybe? None show up, but I also don't know what they are

**Comment by 9mm** [comment]
well it was because of vim-yankstack. If anyone wants to know how to find conflicts its `:verbose map <key>`
