### ISSUE TITLE
2-char labels

### ISSUE THREAD

**Issue by ghost** [justinmk/vim-sneak#232]
```vim
let g:sneak#target_labels = "asdf"
```
I defined it like this because I want to go with left hand only, that makes me easier to move. But after defining this it shows something like that:

```
>ea

sn[a ]k
sn[s ]k
sn[d ]k
sn[f ]k
sneak
```

So I can't reach the last one. In easymotion its like this:

```
ea

sn[aa]k
sn[as]k
sn[ad]k
sn[af]k
sn[ss]k
```

And so on. That means I can do 4! = 24 labels while sneak is 4. If you have 6 letters, that means 6! = 720 labels (a lot) while sneak is 6. 720 labels at the same time should be easier for movement. Maybe add it as option because i dont want to spam spaces :smile:

**Comment by justinmk** [comment]
Current alternative is to use `<Tab>` to label the next batch (or `<BS>` or `<S-Tab>` to go in the other direction).

**Comment by justinmk** [comment]
I understand the use case. If you only start with 4 label chars then it's very common to run out of labels. If you start with 15+ labels then its very _uncommon_ to run out of labels, thus hitting `<Tab>` isn't a high cost.

So this double-char labeling is mostly useful if you restrict the label set.

**Comment by midnio** [comment]
Also, you can implement it in python easily, using itertools.combinations
```python
def combinations(iterable, r):
    # combinations('ABCD', 2) --> AB AC AD BC BD CD
    # combinations(range(4), 3) --> 012 013 023 123
    pool = tuple(iterable)
    n = len(pool)
    if r > n:
        return
    indices = range(r)
    yield tuple(pool[i] for i in indices)
    while True:
        for i in reversed(range(r)):
            if indices[i] != i + n - r:
                break
        else:
            return
        indices[i] += 1
        for j in range(i+1, r):
            indices[j] = indices[j-1] + 1
        yield tuple(pool[i] for i in indices)
```

You can turn it into VimL. It works like
```python
combinations('ABCD', 2) #--> AB AC AD BC BD CD
```

**Comment by midnio** [comment]
I'm not sure if laziness in VimL exists, because this yields an infinite amount of (`while True:`) combinations, and it generates when needed.

**Comment by justinmk** [comment]
Yeah, it's not difficult, it's just hours of my time that  are not a high priority. If you send a PR with some tests, I'll merge it.

**Comment by midnio** [comment]
Actually, I don't know vimL that good. Also creating plugins.
