### ISSUE TITLE
Don't jump to first label hit

### ISSUE THREAD

**Issue by tbo** [justinmk/vim-sneak#233]
Is there a way not to jump to the first hit in label-mode?
I keep my cursor line always vertically centered with `set scrolloff=9999`. This causes the whole viewport to scroll to the first hit, which can be quite disorienting.

**Comment by justinmk** [comment]
No, that defeats one of the central assumptions of the plugin. Sneak is designed for going somewhere with minimal ceremony; label-mode is a fallback for the non-optimal case.
