### ISSUE TITLE
option to disable all syntax highlighting while active

### ISSUE THREAD

**Issue by yashamon** [justinmk/vim-sneak#235]
Beautiful plugin, but is there an option to temporarily set syntax off when invoking sneak? This would mean having less distraction on screen. Also  there seems to be some weird interaction with latex highlighting when more then one match is present.

**Comment by justinmk** [comment]
> sneak-events

See `:help sneak-events` for events which allow you to do what you want. 

However disabling/re-enabling syntax is tricky: in old versions of Vim, that's the approach used by Sneak. But it has two problems:

- https://github.com/justinmk/vim-sneak/issues/197
- https://github.com/justinmk/vim-sneak/issues/202

> Also there seems to be some weird interaction with latex highlighting when more then one match is present.

Most likely that plugin is using the Vim "conceal" feature, which does not support multiple simultaneous usages. Nothing can be done.

**Comment by yashamon** [comment]
Awesome!
I don't know how to go to original syntax determined by filetype, so this
is kinda a hack but worked for me:

au FileType tex autocmd User SneakLeave set syntax=tex
au FileType tex autocmd User SneakEnter set syntax=text
