### ISSUE TITLE
sneak streak + latex-box problems

### ISSUE THREAD

**Issue by notmattmoore** [justinmk/vim-sneak#237]
Hi,

With g:sneak#label=1 and latex-box loaded for a tex file, the labels for things
inside a math environment get prepended with a unicode version of that symbol.
Here's an example.

Say the file has ft=tex, latex-box is loaded, and the file contains

  $\alpha$
  $\alpha$

Pressing sal results in this being shown:

  α
  αs

I'm not sure whether to open this as an issue with latex-box or with sneak.
Sneak is the only plugin I've observed this with, but I also suspect that it's
the only plugin I'm using that makes use of the conceal feature.

MM

**Comment by justinmk** [comment]
You mean, the `α` is _not_ displayed by latex-box (before invoking Sneak)? I would assume latex-box also uses "conceal" to change `\alpha` into `α`.

Labeling works by [searching the buffer](https://github.com/justinmk/vim-sneak/blob/91192d8969af1d86c98beff4001612976ea25d7a/autoload/sneak/label.vim#L49) and getting a result from `searchpos()`. Then the label is placed there. 

There is no way to additionally check if some other conceal thing is concealing things.

**Comment by notmattmoore** [comment]
Thanks for your reply.

The α is not displayed by latex-box. The $\alpha$ is changed to α once sneak mode is invoked, and it changes back to $\alpha$ after leaving sneak mode.

After looking at it a bit more, it looks like *all* characters get changed. If the file is

  $\alpha$ $\alpha$ $\beta$

pressing sal displays

  α αs β

The display reverts back to the original once sneak mode is left.

**Comment by notmattmoore** [comment]
This is caused by setting the conceallevel to a non-zero value. Clearly this isn't a sneak specific issue. Sorry for the noise, I'll have to track this down elsewhere.

**Comment by notmattmoore** [comment]
For anyone else that makes it here, this is a newish vim feature that you can read
about with :help tex-cchar. It can be disabled by setting g:tex_conceal="".
