### ISSUE TITLE
Delete using sneak motion?

### ISSUE THREAD

**Issue by pbbob** [justinmk/vim-sneak#238]
Is it possible to get vim-sneak to work with other operators?
For example, I can do `dtX` to delete until the character `X`. But I want to use vim-sneak to delete until an occurrence of 2 characters (like `dsXY`) is this possible?

**Comment by justinmk** [comment]
"z" is used instead of "s" to avoid conflict with https://github.com/tpope/vim-surround . 

    dzXY

If you don't use https://github.com/tpope/vim-surround then you can change "z" to "s":

```
omap s <Plug>Sneak_s
omap S <Plug>Sneak_S
```

If you use label-mode, then:

```
omap s <Plug>SneakLabel_s
omap S <Plug>SneakLabel_S
```

See also `:help sneak-mappings` and the README.md.
