### ISSUE TITLE
<plug>sneak_s mapping does not work as expected in operator pending mode

### ISSUE THREAD

**Issue by jdhao** [justinmk/vim-sneak#239]
I tried the <plug>Sneak_s mapping in operator pending mode. But it does not work as expected. Here is a minimal config to reproduce:

```
let &runtimepath .= ','.expand('~/.local/share/nvim/plugged/vim-sneak')

let g:sneak#label = 1
nmap f <Plug>Sneak_s
xmap f <Plug>Sneak_s
omap f <Plug>Sneak_s
nmap F <Plug>Sneak_S
xmap F <Plug>Sneak_S
omap F <Plug>Sneak_S
```

Suppose we have the following text in normal mode (`|` indicate the cursor position)
```
|hello world
```

If I press `cfrl` , `r` will be highlighted, 

![image](https://user-images.githubusercontent.com/16662357/57502240-7246d000-731d-11e9-892d-0dbfa127c47f.png)

if I then press any key, only `hello wo` is replaced with that character, character `r` is not included. 
This behaviour is inconsistent with the behaviour of `f`  in normal and visual mode (in visual model, if I press `vfrl`, `hello wor` is correctly selected).

**Comment by justinmk** [comment]
> This behaviour is inconsistent with the behaviour of f in normal and visual mode (in visual model, if I press vfrl, hello wor is correctly selected). 

Sneak includes  f-like and t-like mappings: https://github.com/justinmk/vim-sneak#how-can-i-replace-f-andor-t-with-one-character-sneak

`s` is "exclusive" (see `:help exclusive`).  It doesn't really make sense for multi-character sneak to be inclusive, same as the builtin `/` motion.

**Comment by jdhao** [comment]
if `s` is exclusive, then why does `vfrl` select `hello wor` instead of `hello wo`?

**Comment by justinmk** [comment]
It is exactly the same behavior as `/`.

**Comment by jdhao** [comment]
Can I change it to be inclusive in operator pending mode? The inconsistency often makes me change one less character than I really want...

**Comment by justinmk** [comment]
You can create a custom mapping, see `:help sneak#wrap()` which gives full examples.

**Comment by jdhao** [comment]
Thanks for your help. I was able to do what I want with the following mapping:

```
onoremap <silent> f :call sneak#wrap(v:operator, 2, 0, 1, 1)<cr>
```
