### ISSUE TITLE
Disable match highlighting

### ISSUE THREAD

**Issue by khollbach** [justinmk/vim-sneak#240]
Great plugin; thanks for your hard work :)

I know this has come up before (e.g. #171) but the proposed solution to disable match highlighting doesn't work for me.

The suggested fix, `autocmd ColorScheme * hi! link Sneak Normal`, causes matches to lose their existing highlighting until the sneak is cancelled. E.g., when sneaking for "ea", the matches on lines 6 and 9 lose their color: ![sneak](https://user-images.githubusercontent.com/14352046/58665118-2d9bcc80-82fe-11e9-86b8-9aba96a2fee9.png)

The following _does_ work for me: `autocmd User SneakLeave highlight clear Sneak` (but surprisingly this doesn't: `autocmd ColorScheme * highlight clear Sneak`).

Could we add an option to disable match highlighting? Alternately, please change the docs [here](https://github.com/justinmk/vim-sneak/blob/master/doc/sneak.txt#L368) to `autocmd User SneakLeave hi clear Sneak` in case anyone has the same problem.

**Comment by justinmk** [comment]
> (but surprisingly this doesn't: `autocmd ColorScheme * highlight clear Sneak`).

Because of #108 (for some reason people change their colorschemes at runtime ...). 

Anyways, since 1734d847d008caca16609cf128ff8ea6372c6b25 handling the `ColorScheme` event is no longer needed (unless you like to change colorscheme at runtime, then in that case, yes, use `au user SneakLeave`).
