### ISSUE TITLE
Incosistent exclusive motion when moving backwards

### ISSUE THREAD

**Issue by avalonv** [justinmk/vim-sneak#242]
Thanks for writing this plugin. 
I am having a issue with `dT{2chars}`, I'll do my best to illustrate:

create maps for 2 char t like (exclusive) motions:
```
nnoremap <silent> t :<C-U>call sneak#wrap('',           2, 0, 0, 1)<CR>
nnoremap <silent> T :<C-U>call sneak#wrap('',           2, 1, 0, 1)<CR>
xnoremap <silent> t :<C-U>call sneak#wrap(visualmode(), 2, 0, 0, 1)<CR>
xnoremap <silent> T :<C-U>call sneak#wrap(visualmode(), 2, 1, 0, 1)<CR>
onoremap <silent> t :<C-U>call sneak#wrap(v:operator,   2, 0, 0, 1)<CR>
onoremap <silent> T :<C-U>call sneak#wrap(v:operator,   2, 1, 0, 1)<CR>
```

using forward motion `dtis` (cursor = `[]`) :

```
[t]his is a test
```

Produces:
`is is a test` - fully excludes target `is`

but with reverse motion `dTis`:
```
this is a tes[t]
```

Produces:
`this ist` but I was expecting `this is`, only the first character of "is" was excluded

**Comment by justinmk** [comment]
I assume you mean `onoremap`. 

> using forward motion `dtis` (cursor = `[]`) :
> 
> ```
> [t]his is a test
> ```
> 
> Produces:
> `is a test` - fully excludes target `is`

That should produce (and this works for me) :

    his is a test


> but with reverse motion `dTis`:
> 
> ```
> this is a tes[t]
> ```
> 
> Produces:
> `this it` but I was expecting `this is`, only the first character of "is" was excluded

Wouldn't you expect `this ist` ?

**Comment by avalonv** [comment]
> Wouldn't you expect this ist ?

I rushed writing this issue, but you're right

**Comment by avalonv** [comment]
I didn't include the `onoeramp` in my issue, updated it.

**Comment by justinmk** [comment]
The choice is arbitrary, so it does not make sense to change it. The target of the motion is always the first char; additional chars are just qualifiers.

> but with reverse motion `dTis`:
> 
> ```
> this is a tes[t]
> ```

To get `this ist`, target `<space>a` instead of `is`.
