### ISSUE TITLE
Jumping in reverse with `,` is not working

### ISSUE THREAD

**Issue by 0xACE** [justinmk/vim-sneak#243]
Hi, on my machines sneak is working fine when I jump to next occurances with `;` but nothing happens when I use `,` and I'm expecting it to go backwards to previous occurances.

Is this working on your machines?

**Comment by justinmk** [comment]
what's your configuration? is something mapped to `,` ?

    :verbose map ,

**Comment by 0xACE** [comment]
Sorry, didn't notice that you replied:

I have two bindings caused by `justify.vim`:
```
nmap ,gq :%s/\s\+/ /g<CR>gq1G
vmap ,gq :s/\s\+/ /g<CR>gvgq
```

but even if I `unmap` them the problem remains

It seems like if I remove `runtime macros/justify.vim` in my `.vimrc` the problem disappears...

Any idea on how to just unmap those 2 lines and not affect `,` ? `justify.vim` is shipped by the vanilla binary afaik, so it's not exactly within my own `.vim` folder...

**Comment by justinmk** [comment]
> Any idea on how to just unmap those 2 lines and not affect , ? 

    :help unmap
