### ISSUE TITLE
Extra conceal characters are shown in label-mode

### ISSUE THREAD

**Issue by sch0125** [justinmk/vim-sneak#245]
`Conceal` syntax group may also be used by other plugins. 
`cchars`  shown in label mode contains not only those added by sneak but also whole `cchars` contributed by all the others.

A minimal vimrc to repro:
```vim
call plug#begin('~/.vim/plugged')
  Plug 'Yggdroot/indentLine'
  Plug 'justinmk/vim-sneak'
call plug#end()
set shiftwidth=2
let g:sneak#label = 1
```
Snapshot of failed symptom:

![1](https://user-images.githubusercontent.com/840562/68117516-7fddbb00-ff38-11e9-9e65-4e7a0ded50cf.PNG)

PR #244 attempts to fix this issue.

Snapshot after applying the change:

![222](https://user-images.githubusercontent.com/840562/68117565-b1ef1d00-ff38-11e9-9ebb-54a5f7a7a517.PNG)

**Comment by justinmk** [comment]
thanks, this is a [known issue](https://github.com/justinmk/vim-sneak/issues?q=is%3Aissue+indentLine+is%3Aclosed) but no one proposed using `getmatches()` until https://github.com/justinmk/vim-sneak/pull/244, that seems interesting. Though it seems likely to be slow.

**Comment by sch0125** [comment]
I think that is probably ok, indentLine uses `matchadd` with regex for conceal characters.
The number of matched groups is probably the same as the number of indent levels.

https://github.com/Yggdroot/indentLine/blob/bb548a975ebe4576073ca025eeb2743b4465ce1d/after/plugin/indentLine.vim#L138-L153

https://github.com/Yggdroot/indentLine/blob/bb548a975ebe4576073ca025eeb2743b4465ce1d/after/plugin/indentLine.vim#L310
