### ISSUE TITLE
vim-sneak does not register < character correctly (displays as <80><fc>^B<)

### ISSUE THREAD

**Issue by dseeni** [justinmk/vim-sneak#249]
Hey Justin, 

Love vim-sneak, such an awesome plugin, very clever optimizing for the average case.
I'm stuck to Windows 8.1 pro for work, and Vim-Sneak via Nvim-QT does not register the `<S-lt>` character code that happens when I press "<". So f, t, F, T, and sneak_s/sneak_S do not work with it. 

NeoVim-QT does recognize it though, and the default operators f, t,F,T and search itself work with it just fine when search for "<".

Do you know what would cause this? Is it possible to input specific characters or append sneak to recognize the `<S-lt>` as "<". 

It spits out this weir code as is: 
not found: `<80><fc>^B<`
if I search `<space><`

![image](https://user-images.githubusercontent.com/6591429/78457846-1d612600-7662-11ea-9404-ebbaf7cc8a8e.png)
![image](https://user-images.githubusercontent.com/6591429/78457848-1f2ae980-7662-11ea-88ca-50f96f245cf8.png)

**Comment by justinmk** [comment]
I can reproduce this by sending this to Nvim via the RPC API:

    nvim_input('s <s-lt>')

This is a Neovim-Qt bug, it should not send `shift-<` if you are inputting `<`. That would be like sending `SHIFT + A` for the uppercase "A" character. It should only send the "A" character.

**Comment by dseeni** [comment]
Interesting! Funny, because the default f,F,t,T, and search / ? somehow recognize the <s-LT> code, yet obviously since it's wrong no plugins work well with it. Been noticing similar issues with Tpope's plugins as well.  

I might try to adhoc patch this with Autohotkey, now that I have a better idea why it's not working. Thanks for the reply! I'll check over at Nvim-qt to see if there are is an issue open.

**Comment by justinmk** [comment]
> the default f,F,t,T, and search / ? somehow recognize the code

sneak (and many plugins) use `getchar()`. Perhaps Sneak should discard the modifier ... I am fuzzy about precedent here

**Comment by dseeni** [comment]
![image](https://user-images.githubusercontent.com/6591429/80433664-5af54f80-88ac-11ea-8a2d-07a14fd10942.png)
This works via autohotkey. Incase someone else on windows comes looking. 

I think this is a Nvim-Qt bug and ideally should be fixed there. Especially given that in nvim terminal this is not an issue.

**Comment by justinmk** [comment]
Ah thanks for linking that. It was fixed in https://github.com/equalsraf/neovim-qt/pull/612 , but I think Nvim-Qt hasn't done a release yet.
