### ISSUE TITLE
Any way to do an operation in a line without moving?

### ISSUE THREAD

**Issue by baldore** [justinmk/vim-sneak#250]
Hey Justin, thanks for this great plugin.

I was wondering if there's a way to do an operation (like yy or dd) in a line without moving. I saw this post https://www.reddit.com/r/vim/comments/1yfzg2/does_anyone_actually_use_easymotion/ and the first comment of `jollybobbyroger` has some interesting stuff about how he works. Basically, he uses ranges to go to a point in the document and apply an operation (one example is yanking that line). Not sure if it's possible to create a function that calls `vim-sneak` and then apply the operation you want (something like letting `vim-sneak` to jump to that part and apply `yy''` to come back.

I'm really new to Vim so I'm not sure how to do this, but I think it's more about custom functions. Thanks in advance.

**Comment by baldore** [comment]
At the end I found that <C-x><C-l> can autocomplete lines. I think that's a better way.

**Comment by justinmk** [comment]
> something like letting `vim-sneak` to jump to that part and apply `yy''` to come back.

possible with some scripting. see `:help sneak`
