### ISSUE TITLE
Request: Do not change the input ordering of sneak#target_labels it's so good

### ISSUE THREAD

**Issue by dseeni** [justinmk/vim-sneak#251]
I don't know if this was intentional but this is such a good "feature": 

" SNEAK LABEL PREFERENCE ORDER:
let g:sneak#target_labels = ";asdfjklghiopmenrtucwqzxyvbASDFJKLGHIOPMENRTUCWQZXYVB"

The fact that sneak retains the preference ordering of sneak labels is REALLY awesome. I
I don't know if this was a side effect or intentional based on how the string input is read, but just in case, please keep this "feature" in future releases. 

It's so nice to use all the letters, yet retain an easy to hit preference order. I have NEVER seen this in pycharm or other label jump plugins, so yeah as a side note, Please keep up the awesomeness haha.

**Comment by justinmk** [comment]
Thanks, it's intentional :) The default labels are chosen in an "optimal" way too.
