### ISSUE TITLE
Indent guides are highlighted in window splits that don't have cursor focus

### ISSUE THREAD

**Issue by lynndylanhurley** [justinmk/vim-sneak#252]
It looks like the indent guides (using the [indentLine](https://github.com/Yggdroot/indentLine) plugin) are disabled while using sneak in the current buffer. I'm assuming this is to avoid conflicts with the conceal functionality. This is totally fine and I don't see any issues with the way that this works.

The problem is that the indent guides are still enabled for all of the other window splits, and in those splits the indent guides are highlighted whenever I'm using sneak (see the right pane in the attached screenshot).

![Screen Shot 2020-05-09 at 5 26 48 PM](https://user-images.githubusercontent.com/468037/81486847-5e2dfb00-921d-11ea-8985-f6ef4c42e749.png)

This creates a lot of visual noise and is really annoying when I have a lot of splits open and I'm trying to focus on which character to jump to.

Is there any way to disable the indent guides across all panes while in sneak mode?

Wasn't sure if this was a sneak issue or an indentLine issue so I also posted to Yggdroot/indentLine#308.

**Comment by justinmk** [comment]
AFAIR this is a tradeoff. I think this was fixed in 2014 then it caused some
other problem.

see https://github.com/justinmk/vim-sneak/issues?q=is%3Aissue+indentline+is%3Aclosed

in particular this might be worth reviewing:
https://github.com/justinmk/vim-sneak/issues/227#issuecomment-410106564

**Comment by lynndylanhurley** [comment]
I see that there's a function called [`disable_conceal_in_other_windows`](https://github.com/justinmk/vim-sneak/blob/98a5c946d6dc76528b9d9b044059b5ef1fab5a48/autoload/sneak/label.vim#L150) that runs in the `before` sequence. Would it be possible to call the `indentLine` function [`:IndentLinesDisable`](https://github.com/Yggdroot/indentLine/blob/15aceda8c4eea621b66faa8673fca0b9fbe2f457/after/plugin/indentLine.vim#L209) there, and then call `:IndentLinesEnable` in the `after` sequence?

I just tried hacking at it, but I couldn't get it to work. I don't really know what I'm doing with vim script.

**Comment by justinmk** [comment]
I suppose I would accept such a PR. It's probably slow, but anyone using IndentLines already doesn't care about performance...

**Comment by justinmk** [comment]
https://github.com/justinmk/vim-sneak/pull/303 fixes this for Nvim.
