### ISSUE TITLE
Can't repeat a yank after using the "z" text-object

### ISSUE THREAD

**Issue by lacygoill** [justinmk/vim-sneak#255]
**Describe the bug**

A yank can't be repeated after using the `z` text-object, even if `'cpo'` contains the `y` flag.

**To Reproduce**

Run this shell command (*you'll need to update the paths to the plugins*):

    vim -i NONE -Nu <(cat <<'EOF'
        set rtp^=/path/to/vim-sneak
        set rtp^=/path/to/vim-repeat
        set cpo+=y
        au VimEnter * %d | pu!='abcd' | .t. | update | omap z <plug>Sneak_s
    EOF
    ) /tmp/file

- Press `"Ayzcd` to yank and append `ab` into the register `a`.
- Press `k` to move on the line above.
- Press `.` to repeat `"Ayzcd`.

A new pair of characters is asked.

**Expected behavior**

The last pair of characters is automatically re-used.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/81633713-a6ac0b00-940d-11ea-9bfa-6d9017ee6a79.gif)

**Environment**

 - `vim-sneak` version: https://github.com/justinmk/vim-sneak/commit/98a5c946d6dc76528b9d9b044059b5ef1fab5a48
 - `vim-repeat` version: https://github.com/tpope/vim-repeat/commit/c947ad2b6a16983724a0153bdf7f66d7a80a32ca
 - Vim version: 8.2 Included patches: 1-740
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I tried to fix the issue by replacing this line: https://github.com/justinmk/vim-sneak/blob/98a5c946d6dc76528b9d9b044059b5ef1fab5a48/plugin/sneak.vim#L240

With:

    if is_op && (a:op !=# 'y' || &cpo =~# 'y')

But it doesn't work.

**Comment by lacygoill** [comment]
I don't think this issue can be fixed because a yank doesn't increase `b:changedtick`, and [`vim-repeat` doesn't handle well such an operator](https://github.com/lacygoill/vim-repeat/blob/d276cc7a2869d92c84cbfacab1be1eb540b9caf7/autoload/repeat.vim#L107-L136) (the user may need to invoke `repeat#invalidate()`, but in practice it's not always possible) .  I just thought it was worth being reported.

**Comment by justinmk** [comment]
Yank is not traditionally dot-repeatable in Vim, also.

I see that you also found https://github.com/tpope/vim-repeat/issues/63 ...
