### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by kentosi** [justinmk/vim-sneak#258]
I love this plugin, but is there a way to make the search case insensitive?

**Comment by justinmk** [comment]
`:help sneak` then search for "sensitive" will lead you to the (horribly named, sorry) `g:sneak#use_ic_scs` option.

put this in your config:

    let g:sneak#use_ic_scs = 1

then sneak obeys the 'ignorecase' and 'smartcase' Vim options.
