### ISSUE TITLE
Limit Sneak_[f,F,t,T] matches highlighting to certain number of lines only? 

### ISSUE THREAD

**Issue by oponkork** [justinmk/vim-sneak#260]
Currently, invoking `Sneak_[f,F,t,T]` highlights all the matches it founds. It is not a big issue, but is there a quick way I can limit it to one or two lines above or below the current line? Or say highlight only first 'N' occurrences?

P.S. Thanks for vim-sneak and neovim.

**Comment by justinmk** [comment]
The plumbing is there in the form of a `hasmatches()` function: https://github.com/justinmk/vim-sneak/blob/afe94543bb3bb95ef9ae2a58eebcbc17d69eb304/plugin/sneak.vim#L228

But these kinds of nice-to-have features are generally out of scope.

Thanks for the kind words :)
