### ISSUE TITLE
Defer plugin loading until first use

### ISSUE THREAD

**Issue by voyeg3r** [justinmk/vim-sneak#261]
I use vim-plug to manage my plugins, I would like to be able to defer vim-sneak loading until its first use, so it will not cause any delay on my vim start. Just to give you an example:

    Plug 'mattn/emmet-vim' , { 'for': ['html', 'htmldjango', 'javascript.jsx', 'css'] }

In the above case, emmet-vim will only be loaded for the file formats indicated in the list but it is also possible to associate plugin loading with an event.

[Here](https://junegunn.kr/2014/07/vim-plugins-and-startup-time/) an article about plugin managers and how some of them implement some kind of resource to defer plugin loading.

**Comment by justinmk** [comment]
? `plugin/sneak.vim` is the only thing that eagerly loads; the rest in `autoload/*` is loaded on-demand. The pluginmanager-based deferred loading is a hack offered by pluginmanagers to work around plugins that don't use `autoload/`.
