### ISSUE TITLE
remap `s` to an unsed char

### ISSUE THREAD

**Issue by jeremyjjbrown** [justinmk/vim-sneak#263]
`s` is already a normal mode command.

 s (substitute) will delete the current character and place the user in insert mode with the cursor between the two surrounding characters. 3s , for example, will delete the next three characters and place the user in insert mode.

How do I remap vim sneak to perhaps Leader s so it no longer steps on a useful vim command?

**Comment by jeremyjjbrown** [comment]
Nevermind. Please delete.

**Comment by justinmk** [comment]
For those finding this via search, see https://github.com/justinmk/vim-sneak#how-dare-you-remap-s
