### ISSUE TITLE
Broken text objects in macro

### ISSUE THREAD

**Issue by MRAAGH** [justinmk/vim-sneak#265]
When using the affected text objects in a macro, sometimes the plugin's code appears in the file.

STEPS TO REPRODUCE:

1. start with this file:
```
aaab
aaab
```

2. press these keys:
`ggqqctb,<esc>qj@q`

EXPECTED RESULT:
```
,b
,b
```

ACTUAL RESULT:
```
,b
call <SNR>34_rpt(v:operator, 1)
b
```

**Comment by justinmk** [comment]
i can't reproduce this, tested on nvim 0.5 using the default `s` sneak mapping. 

leave a comment if it's still an issue, with details of the exact vim version. also disable other plugins.

**Comment by MRAAGH** [comment]
Vim version: [nvim 0.5.0](https://files.mazie.rocks/nvimversion)

vimrc used:
```
" Only load vim-sneak, no other plugin or config
set runtimepath^=~/.local/share/vim
call plug#begin('~/.local/share/vim/plugged')
Plug 'justinmk/vim-sneak'
call plug#end()
```

OS: Arch Linux
