### ISSUE TITLE
Label Mode Won't Turn On

### ISSUE THREAD

**Issue by bscuron19** [justinmk/vim-sneak#269]
I am having trouble turning on label mode. On my desktop it works, but on my laptop it does not. I put this line into my .vimrc, but it still stays in the regular vim sneak mode:

let g:sneak#label = 1

Please let me know if I am doing something wrong.

**Comment by bscuron19** [comment]
nvm i needed the conceal feature

**Comment by qubist** [comment]
How did you fix this? I'm having the same issue

**Comment by qubist** [comment]
For anyone else searching, here's the answer:

From the documentation:
```
    1: Enable |sneak-label-mode| if the Vim |+conceal| feature is available.
```
I'm on macOS and Apple's default Vim isn't complied with the +conceal feature. You can use `vim --version` to confirm this.

* `brew install vim` 
* Restart shell

Now `vim --version` or `:version` inside Vim should show `+conceal`
