### ISSUE TITLE
Is it possible to reproduce the behavior of easy-motion j and k using vim sneak

### ISSUE THREAD

**Issue by NikoKS** [justinmk/vim-sneak#270]
I love vim-sneak label mode much more than easy-motion because it's lightweight, doesn't mess with syntax, and compatible with LSP like coc.nvim.

I was able to implement my most needed sneak-motion: labeled 1-character f sneak by following the example on vim-sneak help page

But I'm still missing my second most needed sneak motion, that is go to start of line (similar to easy-motion j and k). I know I can just type the character at the start of the line and sneak there, but It proves to be not too effective as sometimes it ran out of sneak label to use. 

I was wondering If this behavior can be implemented using vim-sneak function? Or if this feature can be implemented? I'm thinking that if I can sneak to right after a newline character '\n' this might be possible?

Thank you for the time. Any help or insights would be most welcome.

**Comment by justinmk** [comment]
> go to start of line (similar to easy-motion j and k). I know I can just type the character at the start of the line and sneak there

You can do it using the SneakEnter event:

    autocmd User SneakLeave norm! ^

That changes the behavior for `s`. Doesn't apply to motion repeat (`;`).

In order to change the behavior only for certain mappings, you would need to map to a function that sets a `++once` handler:

    autocmd User SneakLeave ++once norm! ^
