### ISSUE TITLE
cchars displayed with label highlighting

### ISSUE THREAD

**Issue by BertrandSim** [justinmk/vim-sneak#271]
Hello!

I notice that when sneak-label-mode is enabled, concealed `cchar`s are shown with label highlighting. 

Here is an example with .tex

![image](https://user-images.githubusercontent.com/46756885/113661823-661a4780-96d9-11eb-8ecf-4d42d2e009cb.png)

```vim
" vimrc

call plug#begin('~/.vim/plugged')
  Plug 'lervag/vimtex'
  Plug 'justinmk/vim-sneak'
call plug#end()

let g:sneak#label = 1
```

```tex
% tex

$\alpha$ $\beta$
word word word
```

On the last line, pressing `swo` highlights `α` and `β`, even with `set conceallevel=0`.

* * *
I noticed that there are [similar issues](https://github.com/justinmk/vim-sneak/issues?q=is%3Aissue+indentLine+is%3Aclosed). However, those are specific to the Indent Line plugin. In general, this seems to occur with any buffer that uses `cchar`s. 
I also noticed that #244 attempted to fix this issue, but the bug still persists.

I had a glance at the code for #244, and my hunch is that `getmatches()` only picks up groups defined by `matchadd()` and `:match`, and does not pick up groups defined by 
```vim
syntax match {name} {regex} contained conceal cchar={char}
```

**Comment by justinmk** [comment]
There's no good way to fix this without causing other problems, AFAIK. #252 is a particular case of a general Vim limitation.

**Comment by justinmk** [comment]
https://github.com/justinmk/vim-sneak/pull/303 fixes this for Nvim.
