### ISSUE TITLE
s/S mappings not working after install (nvim nightly)

### ISSUE THREAD

**Issue by molleweide** [justinmk/vim-sneak#278]
Hi Justin,

After installing `s` is not being mapped to sneak it seems. Capital `S` seems to work but not small s. Does this make sense?? I am going to try to trouble shoot more and I'll get back later. Please tell me if this has happended to somebody before or if you want me to try something specific.

I am super excited to try this. I am trying to follow the neovim development and read all the issues that come up. This is so much fun to read the discussions you are having.

**Comment by gegoune** [comment]
You can try to see if something is overriding the mapping. `:verbose map s` might shed some light.

**Comment by molleweide** [comment]
Thanks @gegoune !

the command `:verbose map s` gives me this output:

```
x  s             <Plug>Sneak_s
        Last set from ~/.local/nvim/plugins/vim-sneak/plugin/sneak.vim line 403
n  ss          * <C-W>s
        Last set from ~/.dotfiles/nvim/init.vim line 139
Press ENTER or type command to continue
```

If should say `n  s         <Plug>Sneak_s` right???

**Comment by gegoune** [comment]
Try removing your mapping from `init.vim:139`. It might be causing sneak not to create normal mode mapping (docs do mention it afair).

**Comment by molleweide** [comment]
oh that makes sense actually. I'm stupid for not realizing that!
