### ISSUE TITLE
[Bug Report] No label when too many occurrences of the search chars

### ISSUE THREAD

**Issue by laggardkernel** [justinmk/vim-sneak#280]
When the searched characters occur too many times, there's not enough label. Some of the occurrences are highlighted but without any label set.

**Comment by bruhtus** [comment]
You can add more label by using `g:sneak#target_labels`. Here's an example:
```vim
let g:sneak#target_labels = ';aszxcfvqwertyuiopbnmABCEFGIJKNOPQRSTUVZ'
```

For more info `:help sneak-options`

**Comment by laggardkernel** [comment]
Thanks, I got it. Only one character label is supported, I need to add more characters as label candidate.

**Comment by ggandor** [comment]
@laggardkernel In that case, you can switch to the next set of matches with `tab` (`:h sneak-mappings` -> label mode).

**Comment by glyh** [comment]
I think it would be better if there are multi char label supported, we can take vim-smalls's behavior as reference: 
1. For multiple chars, The last label appear repeatedly.
2. On typing that label, all label refreshes just for matches marked as that label. 
3. Repeat 1~2 until we got a single match.

**Comment by justinmk** [comment]
> I think it would be better if there are multi char label supported, we can take vim-smalls's behavior as reference:

Intentionally not supported. That is clumsy, might as well use `/` at that point.

**Comment by ggandor** [comment]
@justinmk Theoretically Sneak could do the same as Lightspeed, processing two match groups at a time, and showing them with a different background color, indicating that all the matches in the second group are prefixed with `tab`. This adds ~zero mental load as opposed to two-char labels. But I think this cannot be implemented at the moment if relying on Conceal, right? ([related](https://github.com/vim/vim/issues/8730)) Don't you happen to have some idea to work around that? I'd be happy to do a PR _if_ we could figure out something.

**Comment by justinmk** [comment]
> But I think this cannot be implemented at the moment if relying on Conceal, right? ([related](https://github.com/vim/vim/issues/8730)) Don't you happen to have some idea to work around that?

Not possible afaik. But I also don't see why a different color would be any help. The unlabeled matches are pretty recognizable.

**Comment by ggandor** [comment]
You could see the labels right away then, so at least for the second group, the additional short pause would be eliminated.
