### ISSUE TITLE
Re-configuring sneak (in VS-Code) so that "s" and "S" keep their traditional meaning

### ISSUE THREAD

**Issue by tbfe-de** [justinmk/vim-sneak#294]
The header says it all: Is it possible to configure "sneak" to use another command and leave the original "s" and 'S' commands untouched? ('s' to replace the character under the cursor by two or more characters resp. 'S' to replace a whole line by something else slips "from my brain into my fingers" much too automatically that I can avoid it. (And I don't WANT to avoid it.)
Repurposing "s" and 'S'  to do something different than it traditionally did in "vi" since over four decades IMO should be a no-go.

**Comment by justinmk** [comment]
> Repurposing "s" and 'S' to do something different than it traditionally did in "vi" since over four decades IMO should be a no-go.

 it's right in the faq https://github.com/justinmk/vim-sneak#how-dare-you-remap-s

    :help sneak-custom-mappings

```
    nmap x <Plug>Sneak_s
    nmap X <Plug>Sneak_S
