### ISSUE TITLE
allow disabling prompt for cmdheight=0

### ISSUE THREAD

**Issue by jemag** [justinmk/vim-sneak#296]
Is there a way to disable the prompt?

 Currently with cmdheight=0, this will will make using sneak a bit painful since you will get an enter confirmation every time you trigger it : 
![image](https://user-images.githubusercontent.com/7985687/173840975-32203cae-cae6-4436-8437-dbd146700f9a.png)

Using an empty prompt:
```lua
vim.g["sneak#prompt"] = ''
```
will still trigger the prompt, but just remove the `>` character.

**Comment by justinmk** [comment]
PR welcome to change the behavior for `vim.g["sneak#prompt"] = 'NONE'`
