### ISSUE TITLE
Make ; map to most recent f/s usage

### ISSUE THREAD

**Issue by yodigi7** [justinmk/vim-sneak#298]
It would be nice to have `;` overloaded so that it would work as the 'next' character for both `f` and `s` simultaneously. When pressed it will just repeat the most recent search whether it was the `f` search or the `s` search rather than only one or the other.

**Comment by justinmk** [comment]
Not sure I understand. It should already work like that, depending on your configuration. What exactly is your configuration, and what steps did you try?
