### ISSUE TITLE
Is it possible to use ':' to go to a previous search result rather than ','?

### ISSUE THREAD

**Issue by brianxk** [justinmk/vim-sneak#301]
I've remapped ',' to the leader key, so I'm unable to use it in vim-sneak. Is it possible to remap the default ',' to ':' instead?

**Comment by ggandor** [comment]
`[n|x]noremap : <Plug>Sneak_,` (see [`:help sneak-custom-mappings`](https://github.com/justinmk/vim-sneak/blob/93395f5b56eb203e4c8346766f258ac94ea81702/doc/sneak.txt#L94)).
