### ISSUE TITLE
map f failed in pycharm

### ISSUE THREAD

**Issue by chenhui2016** [justinmk/vim-sneak#307]
The quickscope plugin can correctly modify f, f, but not sneak. Even when I uninstalled the quickscope plugin, f became a normal VIM function, and map still failed.Here is my ideavimrc configuration.

![image](https://github.com/justinmk/vim-sneak/assets/66300288/d140d906-b75d-478b-a71a-05ce34cbec6d)

**Comment by joaomcarlos** [comment]
Hi, you might want to checkout the [IdeaVim port](https://github.com/Mishkun/ideavim-sneak) instead.
