### ISSUE TITLE
indentLine char is highlighted as match

### ISSUE THREAD

**Issue by jmlucjav** [justinmk/vim-sneak#48]
I also use indentLine pluging, I am using this char:

```
        let g:indentLine_char = '¦'
```

so if I have a block that is showing that char, when I seach for something with s, the indentLine char is also highlitghted as if it was another match, for example here I did 'sol':
http://i.imgur.com/LJJTkS4.png

I guess this is not on purpose?

thanks

**Comment by yevhen-m** [comment]
I'm still having this bug:
<img width="851" alt="screen shot 2017-06-27 at 7 15 23 am" src="https://user-images.githubusercontent.com/10185058/27570655-7ed4a18c-5b08-11e7-8046-39cd481e6366.png">

```
" Vim-sneak settings {{{
hi SneakLabel ctermfg=white ctermbg=04 cterm=bold
hi Sneak ctermfg=white ctermbg=04 cterm=bold
let g:sneak#label = 1
let g:sneak#use_ic_scs = 1
" }}}

" IndentLine settings {{{
" -------------------------------------------------------------
let g:indentLine_color_term = 19
let g:indentLine_fileType = ['python', 'vim']
nnoremap coi :IndentLinesToggle<cr>
" Dont use indentline_faster with delimitmate
" }}}
```
