### ISSUE TITLE
Setting SneakNext/Previous independently for SneakForward/Backward

### ISSUE THREAD

**Issue by beloglazov** [justinmk/vim-sneak#71]
Hi Justin,

Thanks for the awesome plugin! I have a feature request regarding the key binding configuration. Currently, it's possible to map SneakNext and SneakPrevious; however, the bindings are the same for both directions. It would be great to be able to set these bindings independently for each direction. 

Just to explain why I need this: I'd like to map j/k for going down/up through the matches in the document independently from the direction in which I invoked Sneak. With the current configuration, pressing j lets me go down through the matches if I searched forward, while it goes up if I searched backward, which feels not ideal. I hope this explanation is clear :)

Thanks a lot!

Cheers,
Anton

**Comment by moll** [comment]
That's super. Thanks.
I did notice the `;` behavior after using `F` still remains. You don't reckon it's possible to get that aligned with Sneak's `absolute_dir` option, too?

**Comment by justinmk** [comment]
Hmm, sounds like a bug. Did you restart vim?

**Comment by moll** [comment]
Yep. I've actually mapped `'` to `SneakNext` if that matters:
```
let sneak#streak = 1       " Automatic streak mode.
let sneak#absolute_dir = 1 " ; and , always move forward and backwards.
nmap ' <Plug>SneakNext
```

Are you seeing a different behavior? I'm talking about `F` as in find a single character (not an alias to Sneak).

**Comment by justinmk** [comment]
> I'm talking about F as in find a single character (not an alias to Sneak).

Oh, there's nothing we can do about that, except https://github.com/justinmk/vim-sneak#how-can-i-replace-f-andor-t-with-one-character-sneak

**Comment by moll** [comment]
Ah, superb. I'll try that, thanks!

Mind confirming whether the following is or isn't a bug that you see too?
Given a line `asdf asdf asdf`, when at its end (`$`), typing `Sdf` lands you at the last `df`. Now, pressing `;` or (`'` for me) lands me on the middle `df` (the "sneaks" offered were `s` and `a`). Pressing `;` again, takes me back to the last `df`. I'd say it shouldn't jump to the middle and instead remain at the last `df` (possibly looking for other `df`s rightward if there would be any).

**Comment by justinmk** [comment]
> I'd say it shouldn't jump to the middle and instead remain at the last df (possibly looking for other dfs rightward if there would be any).

Yeah that seems like a bug. Thanks
