### ISSUE TITLE
Highlight other matches in both directions.

### ISSUE THREAD

**Issue by mattboehm** [justinmk/vim-sneak#78]
(Whoops accidentally submitted before adding details.)

I'd prefer to see highlights in both directions rather than just the direction I'm currently going in. I understand that this might make it harder to visually locate the next match, but this could be solved by giving different highlight groups for the forward/backwards matches.

Let me know what you think. I'm happy to take a stab at this and submit a PR if you'd like.

**Comment by PonderingGrower** [comment]
I must add I'd love this feature to become reality. +1

**Comment by mattboehm** [comment]
Whoops, dropped the ball on this. I have an initial implementation up at https://github.com/mattboehm/vim-sneak/tree/reverse-hl . As the commit message mentions, still need to add docs/settings/tests, but first want to ensure the correctness.

When I try to run the vader tests either on master or my branch, I get multiple failures. The number of failures under the exact same conditions is also inconsistent. Do you have any ideas why this might be?

**Comment by justinmk** [comment]
@mattboehm Thanks for that. The simplicity of the implementation is encouraging. 

> When I try to run the vader tests either on master or my branch, I get multiple failures. The number of failures under the exact same conditions is also inconsistent. Do you have any ideas why this might be?

Encoding seems to matter, as well as the version of Vim (newer is better; recent versions of Vim fix some macro/feedkeys bugs).

**Comment by mattboehm** [comment]
Thanks!
