### ISSUE TITLE
Thoughts on the let g:sneak#streak = 1 feature

### ISSUE THREAD

**Issue by lydell** [justinmk/vim-sneak#88]
I’ve been using vim-sneak for a while, and I really like it! Most of the time it takes me exactly where I want to go really fast.

Every now and then, though, I choose two particularly bad characters to sneak for, and the screen gets all magenta. Suddenly my target might be like 10 <kbd>;</kbd> away (but I cannot be sure that it’s exactly 10, so usually I find myself spamming <kbd>;</kbd> instead of doing <kbd>10;</kbd>). In those cases I either try to find a less common pair of characters close to my original target to sneak for those, or I use some other motion to get a bit closer and then sneak again.

A few weeks ago, I decided to give the let g:sneak#streak = 1 feature a try. My first impression was “Wow, this is brilliant!” when one of those “screen got all magenta” scenarios happened. Suddenly my target was just a single keystroke (the label character) away. It felt like it really sped me up—without changing the sneak experience I’ve gotten used to at all (except that the highlighted matches now are covered with some letter and a space, but that doesn’t matter since I know what I sneaked for).

However, after some time I realized that this option actually slowed me down. Many times a sneak gets many results, but I actually want to go to the first result. Then I usually want to edit the text at that point, for example by typing <kbd>a</kbd> or <kbd>cw</kbd>. But 'a' and 'c' are likely a label to jump to another match! It’s really annoying to press <kbd>a</kbd> to append some text after the cursor, but instead be taken to some other place! That caused my to press <kbd>Esc</kbd> after most sneaks, _increasing_ the number of keystrokes!

I’ve thought about changing the labels, so they won’t likely collide with other commands, but I can’t come up with such a set.

So what first seemed to be a really convenient option did not work out very well in the end. Now I have disabled the option and bound SneakStreak to its own key.

However, I still turn the screen all magenta every now and then. Now, I usually re-perform my sneak using my SneakStreak key followed by <kbd>enter</kbd> instead. That works pretty good ... but it feels like we could do better, just like the let g:sneak#streak = 1 option tries to.

What about the following? If there are more than two matches, give labels to every match. But don’t go to the match if the label is typed: Make every key work just as normal instead. If I _do_ want to follow a label, I have to press my SneakStreak key first. This is how I’m thinking:

I sneak for something. Then one of three things usually happen:
- I get to my target immediately. Great—let’s start editing, without fear that I will be unexpectedly taken to some other place!
- I get to one match too early from my target. No worries, I just hit <kbd>;</kbd> once and I’m there!
- The characters I sneaked for happened to be really common, so there are lots of matches and my target is far away. Then I could just look at the label of my target, press the special key and then the label to get there. This is better that re-performing the sneak using SneakStreak, because: (1) one less keystroke (I don’t have to press <kbd>enter</kbd>) and (2) because the label is already there.

**Comment by justinmk** [comment]
AFAICT everything here worth implementing, was implemented.
