### ISSUE TITLE
Customise behavior of f/F/t/T when used after an F or a T

### ISSUE THREAD

**Issue by kshenoy** [justinmk/vim-sneak#95]
1. Currently f/t always search in the direction of motion and F/T in the opposite direction. Would it be possible to customize it allowing F/T to always search backward and f/t to always search forward?

For eg. pressing `FbFF` will allow moving to the 3rd *b* located before the cursor.

2. Would it be possible to enhance the vertical scoping by highlighting the vertical region after I press `5s` so that it can provide a visual guide whether the character-pair I'm targeting falls within it or not? Currently, the column shows up after I've already moved to the place I'm interested in limiting its utility.

3. Could you explain/point me towards something that explains what exactly streak-mode is? I read the section [Streak-mode features](https://github.com/justinmk/vim-sneak/blob/master/doc/sneak.txt#L216-L228) but that didn't help much.

Thanks a lot

**Comment by kshenoy** [comment]
Hello Justin, any progress on this yet?

**Comment by justinmk** [comment]
Not yet. I'll try to knock it out this weekend.

**Comment by justinmk** [comment]
> Would it be possible to customize it allowing F/T to always search backward and f/t to always search forward?

Now available with this option:

    let g:sneak#absolute_dir = 1

**Comment by kshenoy** [comment]
Thanks! :)
