### ISSUE TITLE
Targets remain highlighted after jump in streak mode -- bug?

### ISSUE THREAD

**Issue by mon10a** [justinmk/vim-sneak#98]
I just updated and see that target highlighting now remains ON after jumping to a match in streak mode. I think the previous behavior which turned the highlighting off immediately after you jump (but turns it back on if you press ';' or ',') is preferable.

Thanks.

**Comment by bebound** [comment]
Hi,
I face this problem now.
I'm using OS X 10.10.3, iTerm2 and Vim7.4.712
The highlight won't clear after jump, works OK on MacVim.
![screen shot 2015-06-26 at 20 05 30](http://i.imgur.com/IkBSnFe.png)

**Comment by justinmk** [comment]
@bebound What are the exact steps to reproduce?

**Comment by bebound** [comment]
I use a minimal vimrc, which only include vim-sneak: https://gist.github.com/bebound/e1c97f00a2a9e6d7fe49
It works like this: [![asciicast](https://asciinema.org/a/bli1q0x3r63v3pyjeyy3aods4.png)](https://asciinema.org/a/bli1q0x3r63v3pyjeyy3aods4)
1 Search for some word.
2 Jump to somewhere
3 The highlighted character remain highlighted

**Comment by justinmk** [comment]
@bebound Are you certain the Vim you're running in iTerm2 is Vim7.4.712 (check `:version`)? What version is MacVim?

**Comment by bebound** [comment]
Yes, both of them are 7.4.712. I install them by home brew and home brew cask.



—
通过 Mailbox 发送

**Comment by justinmk** [comment]
If you're using the exact same Vim in terminal and gui, yet one works and the other doesn't, I don't know how to help you. I can only mention that installing MacVim via homebrew does not overwrite the default OS X Vim unless you explicitly tell it to. So, please verify that the Vim you're running in terminal really is what you think it is.

**Comment by bebound** [comment]
Do you using OS X? Maybe this is compatibility problem on OS X. It's OK on 7.4.273 on Ubuntu.

I record one more screenshot, it shows that:
1 If search result has 2 match (the first character doesn't change), the highlight will be remove after jump.
2 If search result has more than 2 match( the first character changes), the highlight will remain.
2.1 Search another 2 match won't clear the previous wrong highlight.
2.2 Search another 3 match will clear the previous wrong highlight.

 [![asciicast](https://asciinema.org/a/05w7bn93fkpseecih1zlgwspf.png)](https://asciinema.org/a/05w7bn93fkpseecih1zlgwspf)

**Comment by justinmk** [comment]
I OS X every day, this problem doesn't exist in Vim nor Neovim. My guess is it's a bug in a recent patch of Vim. Try upgrading to 7.4.77x or perhaps report it to Vim.

**Comment by bebound** [comment]
Solved by adding "syntax on" in my vimrc....

**Comment by justinmk** [comment]
@bebound Thanks for the tip. Does that mean you normally don't turn syntax on?

**Comment by bebound** [comment]
Yes.
I usually use mccvim, and it looks normally without `syntax on`...

Here is the vimrc https://github.com/bebound/Dotfiles/blob/master/.vimrc

**Comment by justinmk** [comment]
Ok, I may be able to fix that.

**Comment by gyermolenko** [comment]
I have same problem, "Targets remain highlighted after jump in streak mode".
My OS is ubuntu based (15.04). 
vim version is 7.4.488
I've tried both in vim and gvim.
Syntax was on from the beginning. Turning off and on again didn't help
